// GENERATED by tools/gen_catalog_cpp.py from main.dol table 0x8052C1A0 -- do not edit.
#include "shadow/gameplay/SetSystem.hpp"

namespace shadow::gameplay {
namespace {
const SetParamDesc kP1[] = {  // Sample
    {SetParamType(4), "Single", 0, 0, 0, 0.0f, 0.0f, 100.0f},
    {SetParamType(3), "Hex", 0, 0, 256, 0.0f, 0.0f, 0.0f},
    {SetParamType(2), "Uint32", 0, 0, 100, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "Sint32", 1, 0, 100, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "Sint32", 2, 0, 100, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "Sint32", 3, 0, 100, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "Sint32", 4, 0, 100, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "Sint32", 5, 0, 100, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "Sint32", 6, 0, 100, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "Sint32", 7, 0, 100, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "Sint32", 8, 0, 100, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "Sint32", 9, 0, 100, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "Sint32", 10, 0, 100, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "Sint32", 11, 0, 100, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "Sint32", 12, 0, 100, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "Sint32", 13, 0, 100, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP2[] = {  // CONTAINER
    {SetParamType(1), "model", 0, 0, 2, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "select", 0, 0, 6, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "value", 0, 0, 3600, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP3[] = {  // HRD_CONTAINER
    {SetParamType(1), "model", 0, 0, 2, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "select", 0, 0, 6, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "value", 0, 0, 3600, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP4[] = {  // UNBRK_CONTAINER
    {SetParamType(1), "kind", 0, 0, 2, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP5[] = {  // WEAPON_CONTAINER
    {SetParamType(1), "kind", 0, 0, 2, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "weapon", 1, 1, 71, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP6[] = {  // SECRET CONTAINER
    {SetParamType(1), "weapon", 1, 1, 71, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP7[] = {  // BALLOON
    {SetParamType(1), "type", 0, 0, 2, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "item", 0, 0, 7, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "sec", 0, 0, 0, 0.0f, 0.0f, 3600.0f},
    {SetParamType(4), "radius", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "X", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Y", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Z", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
};
const SetParamDesc kP8[] = {  // SPRING
    {SetParamType(4), "level", 0, 0, 0, 0.0f, 0.0f, 15.0f},
    {SetParamType(4), "nocontrol time (sec)", 0, 0, 0, 0.0f, 0.0f, 3600.0f},
};
const SetParamDesc kP9[] = {  // DASHPANEL
    {SetParamType(4), "level", 0, 0, 0, 0.0f, 0.0f, 15.0f},
    {SetParamType(4), "nocontrol time (sec)", 0, 0, 0, 0.0f, 0.0f, 3600.0f},
};
const SetParamDesc kP10[] = {  // JUMP_BOARD
    {SetParamType(4), "level", 0, 0, 0, 0.0f, 0.0f, 15.0f},
    {SetParamType(4), "angle", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "nocontrol time (sec)", 0, 0, 0, 0.0f, 0.0f, 3600.0f},
};
const SetParamDesc kP11[] = {  // RING
    {SetParamType(1), "type", 0, 0, 3, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "num", 1, 1, 128, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "param0", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "param1", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(1), "ghost", 0, 0, 1, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP12[] = {  // LONGSPRING
    {SetParamType(4), "level", 0, 0, 0, 0.0f, 0.0f, 15.0f},
    {SetParamType(4), "nocontrol time (sec)", 0, 0, 0, 0.0f, 0.0f, 3600.0f},
};
const SetParamDesc kP13[] = {  // SAVEPOINT
    {SetParamType(1), "priority", 1, 1, 31, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP14[] = {  // WEIGHT
    {SetParamType(1), "type", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "height", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "intv upper(sec)", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "intv lower(sec)", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "intv damage(sec)", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(1), "sw", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "scale X", 0, 0, 0, 1.0f, 1.0f, 65536.0f},
    {SetParamType(4), "scale Y", 0, 0, 0, 1.0f, 1.0f, 65536.0f},
    {SetParamType(4), "scale Z", 0, 0, 0, 1.0f, 1.0f, 65536.0f},
};
const SetParamDesc kP15[] = {  // GOALRING
    {SetParamType(1), "color", 0, 0, 7, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP16[] = {  // SWITCH
    {SetParamType(1), "type", 0, 0, 2, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP17[] = {  // DASHRING
    {SetParamType(4), "level", 0, 0, 0, 0.0f, 0.0f, 15.0f},
    {SetParamType(4), "nocontrol time (sec)", 0, 0, 0, 0.0f, 0.0f, 3600.0f},
};
const SetParamDesc kP18[] = {  // TARGETSWITCH
    {SetParamType(4), "X", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Y", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Z", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "sec", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "pause", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(1), "hitpoint", 2, 2, 10, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP20[] = {  // FAN
    {SetParamType(1), "type", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "form", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "X", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "Y", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "Z", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "power", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "sec_active", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "sec_negative", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(1), "disp", 1, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "Id", -1, -1, 255, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP24[] = {  // BRK_OBJ
    {SetParamType(1), "kind", 0, 0, 1, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP25[] = {  // CAGE
    {SetParamType(1), "model", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "scale X", 0, 0, 0, 1.0f, 1.0f, 10.0f},
    {SetParamType(4), "scale Y", 0, 0, 0, 1.0f, 1.0f, 10.0f},
    {SetParamType(4), "scale Z", 0, 0, 0, 1.0f, 1.0f, 10.0f},
};
const SetParamDesc kP26[] = {  // CAPTURE_CAGE
    {SetParamType(4), "N/A", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "N/A", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "N/A", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP27[] = {  // HINTRING
    {SetParamType(1), "Message Id", 0, 0, 65536, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "Brunch", -1, -1, 65536, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "range", 0, 0, 0, 10.0f, 0.0f, 65536.0f},
    {SetParamType(4), "sec", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(1), "navi", 7, 0, 7, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP28[] = {  // UD_REEL
    {SetParamType(4), "length", 0, 0, 0, 1.0f, 1.0f, 65536.0f},
    {SetParamType(4), "pos", 0, 0, 0, 1.0f, 1.0f, 65536.0f},
    {SetParamType(4), "angle", 0, 0, 0, 0.0f, -90.0f, 90.0f},
    {SetParamType(4), "power", 0, 0, 0, 400.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP29[] = {  // ITEM_BOX
    {SetParamType(1), "item", 0, 0, 10, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP32[] = {  // FIRE
    {SetParamType(4), "scale X", 0, 0, 0, 1.0f, 0.5f, 2.0f},
    {SetParamType(4), "scale Y", 0, 0, 0, 1.0f, 0.5f, 2.0f},
    {SetParamType(4), "scale Z", 0, 0, 0, 1.0f, 0.5f, 2.0f},
};
const SetParamDesc kP33[] = {  // ENERGY_CORE
    {SetParamType(1), "type", 0, 0, 1, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP34[] = {  // POISON_GAS
    {SetParamType(4), "scale X", 0, 0, 0, 1.0f, 0.5f, 2.0f},
    {SetParamType(4), "scale Y", 0, 0, 0, 1.0f, 0.5f, 2.0f},
    {SetParamType(4), "scale Z", 0, 0, 0, 1.0f, 0.5f, 2.0f},
};
const SetParamDesc kP36[] = {  // ROCKET
    {SetParamType(4), "angle", 0, 0, 0, 0.0f, 0.0f, 360.0f},
    {SetParamType(4), "distance", 0, 0, 0, 10.0f, 0.0f, 10000.0f},
};
const SetParamDesc kP37[] = {  // SET_VEHICLE
    {SetParamType(1), "Vehicle", 1, 1, 13, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP38[] = {  // SET_WEAPON
    {SetParamType(1), "weapon", 1, 1, 71, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP39[] = {  // SET_CHARACTOR
    {SetParamType(1), "Characotr", 1, 1, 19, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "ContactRange(m)", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP40[] = {  // BlockChange
    {SetParamType(1), "Type", 0, 0, 0, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "On/Off", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "Radius", 0, 0, 0, 10.0f, 1.0f, 10000.0f},
    {SetParamType(1), "BLOCK", -1, -1, 99, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "BLOCK", -1, -1, 99, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "BLOCK", -1, -1, 99, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "BLOCK", -1, -1, 99, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP41[] = {  // CATCHSTICK
    {SetParamType(4), "length", 0, 0, 0, 10.0f, 1.0f, 65536.0f},
};
const SetParamDesc kP42[] = {  // PARTICLE
    {SetParamType(1), "number", 0, -65536, 65536, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "scale X", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "scale Y", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "scale Z", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP44[] = {  // SETCOLLISION
    {SetParamType(1), "kind", 0, 0, 12, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "form", 0, 0, 2, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "X", 0, 0, 0, 10.0f, 0.1f, 65536.0f},
    {SetParamType(4), "Y", 0, 0, 0, 10.0f, 0.1f, 65536.0f},
    {SetParamType(4), "Z", 0, 0, 0, 10.0f, 0.1f, 65536.0f},
    {SetParamType(1), "Id", 0, 0, 255, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "appear", 0, 0, 2, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP46[] = {  // LIGHT_COLI
    {SetParamType(1), "Type", 0, 0, 2, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "Shape", 0, 0, 2, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "LightFlag", 1, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "LightNumber", 0, 0, 15, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "EffectFlag", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "EffectNumber", 0, 0, 65536, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "ScaleX", 0, 0, 0, 10.0f, 0.0f, 65536.0f},
    {SetParamType(4), "ScaleY", 0, 0, 0, 10.0f, 0.0f, 65536.0f},
    {SetParamType(4), "ScaleZ", 0, 0, 0, 10.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP47[] = {  // HINT COLLISION
    {SetParamType(1), "form", 0, 0, 2, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "X", 0, 0, 0, 10.0f, 0.1f, 65536.0f},
    {SetParamType(4), "Y", 0, 0, 0, 10.0f, 0.1f, 65536.0f},
    {SetParamType(4), "Z", 0, 0, 0, 10.0f, 0.1f, 65536.0f},
    {SetParamType(1), "Message Id", 0, 0, 65536, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "Brunch", -1, -1, 65536, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "range", 0, 0, 0, 10.0f, 0.0f, 65536.0f},
    {SetParamType(4), "sec", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(1), "flag", 7, 0, 7, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "appear", 0, 0, 1, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP48[] = {  // DebugDebugMissionClearCollision
    {SetParamType(2), "0:DK 1:NM 2:HR 3:BOSS", 0, 0, 3, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP49[] = {  // DARKSPINENTRANCE
    {SetParamType(4), "radius", 0, 0, 0, 10.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP50[] = {  // SET GENERATOR
    {SetParamType(1), "ComId", 0, 0, 255, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "Id", 0, 0, 255, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "num", 0, 0, 65536, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "delay", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(1), "scoreId", 0, 0, 65536, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP51[] = {  // MissionClearCollision
    {SetParamType(2), "0:DK 1:NM 2:HR", 0, 0, 2, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "COLLI_RADIUS point", 0, 0, 0, 50.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP53[] = {  // TANK
    {SetParamType(1), "model", 0, 0, 65536, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "blast", 0, 0, 65536, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP54[] = {  // SET_SE_LOOP
    {SetParamType(3), "SEID", 0, 0, 1048575, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "TYPE", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "RangeType", 0, 0, 2, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "ColliParam0", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "ColliParam1", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "ColliParam2", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "DampingRate", 0, 0, 0, 0.5f, 0.0f, 1.0f},
};
const SetParamDesc kP55[] = {  // SET_SE_ONESHOT
    {SetParamType(3), "SEID", 0, 0, 1048575, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "TYPE", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "RangeType", 0, 0, 3, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "ColliParam0", 0, 0, 0, 10.0f, 0.0f, 65536.0f},
    {SetParamType(4), "ColliParam1", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "ColliParam2", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP90[] = {  // STICK
    {SetParamType(1), "model", 0, 0, 65536, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "weapon", 1, 1, 71, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP91[] = {  // TURNOVER
    {SetParamType(1), "model", 0, 0, 65536, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "blast", 0, 0, 65536, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP92[] = {  // ART WORK
    {SetParamType(1), "model", 0, -65536, 65536, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "scale X", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "scale Y", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "scale Z", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP93[] = {  // ART WORK ZONE
    {SetParamType(1), "model", 0, -65536, 65536, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "scale X", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "scale Y", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "scale Z", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP94[] = {  // ART GADGET
    {SetParamType(1), "model", 0, 0, 65536, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP95[] = {  // ART GADGET ZONE
    {SetParamType(1), "model", 0, 0, 65536, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP96[] = {  // FOOTING
    {SetParamType(1), "model", 0, 0, 65536, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP97[] = {  // MOVE_FOOTING
    {SetParamType(1), "model", 0, 0, 65536, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "type", 0, 0, 6, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "spd", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "acc", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "pause", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "pos", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "param0", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "param1", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "param2", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "pause damage", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
};
const SetParamDesc kP98[] = {  // ELEVATOR
    {SetParamType(1), "model", 0, 0, 65536, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "distance", 0, 0, 0, 10.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "speed", 0, 0, 0, 0.5f, 0.0f, 65536.0f},
    {SetParamType(4), "range", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP99[] = {  // DOOR
    {SetParamType(1), "type", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "model", 0, 0, 256, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "width", 0, 0, 0, 100.0f, 1.0f, 10000.0f},
    {SetParamType(4), "height", 0, 0, 0, 100.0f, 1.0f, 10000.0f},
    {SetParamType(4), "depth", 0, 0, 0, 100.0f, 1.0f, 10000.0f},
    {SetParamType(4), "X", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Y", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Z", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
};
const SetParamDesc kP100[] = {  // DAMAGE BLOCK
    {SetParamType(1), "kind", 0, 0, 65536, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP101[] = {  // FAN STAGE
    {SetParamType(1), "type", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "form", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "X", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "Y", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "Z", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "power", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "sec_active", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "sec_negative", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(1), "disp", 1, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "Id", -1, -1, 255, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP124[] = {  // FIRE_VINE
    {SetParamType(4), "radius", 0, 0, 0, 100.0f, 1.0f, 10000.0f},
    {SetParamType(4), "attack sec", 0, 0, 0, 1.0f, 0.0f, 10000.0f},
    {SetParamType(4), "revive sec", 0, 0, 0, 1.0f, 0.0f, 10000.0f},
};
const SetParamDesc kP125[] = {  // BREAKWALL
    {SetParamType(1), "model", 0, 0, 65536, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP126[] = {  // NOBI_KUSA
    {SetParamType(4), "level", 0, 0, 0, 0.0f, 0.0f, 7.0f},
    {SetParamType(4), "angle", 0, 0, 0, 0.0f, 0.0f, 360.0f},
    {SetParamType(4), "sec", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "length", 0, 0, 0, 4.0f, 1.0f, 65536.0f},
    {SetParamType(4), "charge", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP127[] = {  // CATAPULT
    {SetParamType(1), "model", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "level", 0, 0, 0, 0.0f, 0.0f, 15.0f},
    {SetParamType(4), "nocontrol time (sec)", 0, 0, 0, 0.0f, 0.0f, 3600.0f},
    {SetParamType(4), "X", 0, 0, 0, 0.0f, 0.0f, 360.0f},
    {SetParamType(4), "Y", 0, 0, 0, 0.0f, 0.0f, 360.0f},
    {SetParamType(4), "Z", 0, 0, 0, 0.0f, 0.0f, 360.0f},
};
const SetParamDesc kP129[] = {  // E_B_COLI
    {SetParamType(4), "X", 0, 0, 0, 100.0f, 1.0f, 10000.0f},
    {SetParamType(4), "Y", 0, 0, 0, 100.0f, 1.0f, 10000.0f},
    {SetParamType(4), "Z", 0, 0, 0, 100.0f, 1.0f, 10000.0f},
    {SetParamType(1), "type", 0, 0, 8, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "sec", 0, 0, 0, 1.0f, 0.0f, 10000.0f},
    {SetParamType(4), "N/A", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
};
const SetParamDesc kP131[] = {  // TORNADO
    {SetParamType(2), "TURN 0:L 1:R", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "TURN_SPEED m/s", 0, 0, 0, 50.0f, 0.1f, 65536.0f},
    {SetParamType(4), "UP_SPEED m/s", 0, 0, 0, 20.0f, 0.1f, 65536.0f},
    {SetParamType(4), "CYLINDER_R m", 0, 0, 0, 20.0f, 1.0f, 65536.0f},
    {SetParamType(4), "CYLINDER_Y m", 0, 0, 0, 40.0f, 1.0f, 65536.0f},
    {SetParamType(4), "CYLINDER_OFFSET_Y m", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "LAUNCH_X deg", 0, 0, 0, -30.0f, -180.0f, 180.0f},
    {SetParamType(4), "LAUNCH_Y deg", 0, 0, 0, 0.0f, -180.0f, 180.0f},
    {SetParamType(4), "LAUNCH_SPEED m/s", 0, 0, 0, 100.0f, 0.1f, 65536.0f},
    {SetParamType(4), "NO_CONTROL sec", 0, 0, 0, 3.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP132[] = {  // TORNADO_COLLI
    {SetParamType(4), "Radius", 0, 0, 0, 50.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP133[] = {  // ROLL_CIRCLE
    {SetParamType(2), "MODEL 0:Big 1:Sml 2:Head", 0, 0, 2, 0.0f, 0.0f, 0.0f},
    {SetParamType(2), "OBJ_NUM", 4, 1, 32, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "RADIUS m", 0, 0, 0, 20.0f, 1.0f, 65536.0f},
    {SetParamType(4), "CIRCLE_SPD deg/sec", 0, 0, 0, 0.0f, -1080.0f, 1080.0f},
    {SetParamType(4), "OBJ_ANGSPD_X deg/sec", 0, 0, 0, 0.0f, -1080.0f, 1080.0f},
    {SetParamType(4), "OBJ_ANGSPD_Y deg/sec", 0, 0, 0, 0.0f, -1080.0f, 1080.0f},
    {SetParamType(4), "OBJ_ANGSPD_Z deg/sec", 0, 0, 0, 0.0f, -1080.0f, 1080.0f},
};
const SetParamDesc kP134[] = {  // STONE_POLE
    {SetParamType(2), "0:FLAT 1:SLOPE 2:AIR", 0, 0, 2, 0.0f, 0.0f, 0.0f},
    {SetParamType(2), "FALL L/R 0:L 1:R", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "RANGE_R m", 0, 0, 0, 10.0f, 0.0f, 65536.0f},
    {SetParamType(4), "RANGE_HEIGHT m", 0, 0, 0, 15.0f, 0.0f, 65536.0f},
    {SetParamType(4), "ROLLING_SPD m/sec", 0, 0, 0, 5.0f, 0.0f, 65536.0f},
    {SetParamType(4), "ROLLING_DISTANCE m", 0, 0, 0, 50.0f, 0.0f, 65536.0f},
    {SetParamType(2), "STEP_2 0:SOFT 1:HARD", 1, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(2), "STEP_3 0:SOFT 1:HARD", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(2), "STEP_4 0:SOFT 1:HARD", 1, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(2), "STEP_5 0:SOFT 1:HARD", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(2), "STEP_6 0:SOFT 1:HARD", 1, 0, 1, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP135[] = {  // STONE_STATUE
    {SetParamType(2), "ACTIVE 0:off 1:On", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(2), "MIRROR 0:off 1:On", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "RANGE_RADIUS m", 0, 0, 0, 10.0f, 0.0f, 65536.0f},
    {SetParamType(4), "RANGE_HEIGHT m", 0, 0, 0, 6.5f, 0.0f, 65536.0f},
};
const SetParamDesc kP136[] = {  // POWER_DEVICE_CAGE
    {SetParamType(2), "MODEL 0:Out 1:In", 0, 0, 1, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP137[] = {  // EggFleet
    {SetParamType(2), "0:BATTLE 1:MOTHER", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "RANGE_R m", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "RANGE_HEIGHT m", 0, 0, 0, 50.0f, 0.0f, 65536.0f},
    {SetParamType(4), "MOVE_LENGHT m", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "MOVE_SPEED m/s", 0, 0, 0, 2.0f, 0.0f, 65536.0f},
    {SetParamType(4), "FIRE_TIMING s", 0, 0, 0, 20.0f, 0.1f, 65536.0f},
};
const SetParamDesc kP138[] = {  // POWER_DEVICE_NAKED
    {SetParamType(2), "MODEL 0:Out 1:In", 0, 0, 1, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP139[] = {  // RainEffect
    {SetParamType(4), "COLLI_WIDTH m", 0, 0, 0, 20.0f, 0.0f, 65536.0f},
    {SetParamType(4), "COLLI_HEIGHT m", 0, 0, 0, 20.0f, 0.0f, 65536.0f},
    {SetParamType(4), "COLLI_DEPTH m", 0, 0, 0, 20.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP141[] = {  // CIRCUS_BALL
    {SetParamType(1), "type", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "level", 0, 0, 0, 0.0f, 0.0f, 15.0f},
    {SetParamType(4), "nocontrol time (sec)", 0, 0, 0, 0.0f, 0.0f, 3600.0f},
    {SetParamType(4), "angle", 0, 0, 0, 0.0f, 0.0f, 360.0f},
};
const SetParamDesc kP144[] = {  // Chao
    {SetParamType(2), "0:CHAO 1:CHEEZ", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "MOVE_RADIUS m", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "MOVE_SPPED m/sec", 0, 0, 0, 0.5f, -65536.0f, 65536.0f},
};
const SetParamDesc kP145[] = {  // Monster
    {SetParamType(4), "MIN_SPPED m/sec", 0, 0, 0, 30.0f, 0.0f, 65536.0f},
    {SetParamType(4), "MAX_SPPED m/sec", 0, 0, 0, 50.0f, 0.0f, 65536.0f},
    {SetParamType(4), "ACCEL m/sec^2", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "DECEL m/sec^2", 0, 0, 0, 150.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP146[] = {  // MonsterControl
    {SetParamType(1), "0:START 1:MISS 2:END", 0, 0, 2, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "X_LENGTH m", 0, 0, 0, 10.0f, 0.0f, 65536.0f},
    {SetParamType(4), "Y_LENGTH m", 0, 0, 0, 10.0f, 0.0f, 65536.0f},
    {SetParamType(4), "Z_LENGTH m", 0, 0, 0, 10.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP148[] = {  // Coaster
    {SetParamType(2), "PATH_NO", 0, 0, 100, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "MOVE_SPPED m/sec", 0, 0, 0, 50.0f, 0.01f, 65536.0f},
    {SetParamType(4), "LAUNCH_SPD m/sec", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "LAUNCH_ANG deg", 0, 0, 0, 0.0f, -90.0f, 90.0f},
    {SetParamType(4), "LAUNCH_NO_CTRL_TIME sec", 0, 0, 0, 0.0f, 0.0f, 100.0f},
};
const SetParamDesc kP149[] = {  // ThreatObj
    {SetParamType(2), "MODEL_TYPE", 0, 0, 0, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "RANGE_RADIUS m", 0, 0, 0, 5.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP150[] = {  // PARK_BALLOON
    {SetParamType(4), "Height", 0, 0, 0, 10.0f, 0.0f, 3600.0f},
    {SetParamType(4), "Radius", 0, 0, 0, 10.0f, 0.0f, 3600.0f},
    {SetParamType(4), "MinSpeed", 0, 0, 0, 0.1f, 0.0f, 3600.0f},
    {SetParamType(4), "MaxSpeed", 0, 0, 0, 1.0f, 0.0f, 3600.0f},
    {SetParamType(1), "Num", 1, 1, 100, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "MaxNum", 1, 1, 100, 0.0f, 0.0f, 0.0f},
    {SetParamType(3), "Rate", 67371265, 0, 2147483647, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "Sec", 0, 0, 0, 5.0f, 0.0f, 3600.0f},
    {SetParamType(1), "Id", 0, 0, 255, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP151[] = {  // SHOOTING_PANEL
    {SetParamType(1), "Id", 1, 1, 255, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP152[] = {  // GONG
    {SetParamType(4), "speed", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
};
const SetParamDesc kP153[] = {  // CandleStick
    {SetParamType(1), "SAME_COMID_SWITCH_NUM", 1, 1, 256, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP154[] = {  // CIRCUS_POLE
    {SetParamType(4), "scale Y", 0, 0, 0, 1.0f, 0.1f, 1000.0f},
};
const SetParamDesc kP155[] = {  // MORPHDOOR
    {SetParamType(1), "type", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "model", 0, 0, 256, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "width", 0, 0, 0, 100.0f, 1.0f, 10000.0f},
    {SetParamType(4), "height", 0, 0, 0, 100.0f, 1.0f, 10000.0f},
    {SetParamType(4), "depth", 0, 0, 0, 100.0f, 1.0f, 10000.0f},
    {SetParamType(4), "X", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Y", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Z", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
};
const SetParamDesc kP157[] = {  // FallBuilding
    {SetParamType(1), "0:ANT15 1:ANT30 2:BLDG", 0, 0, 2, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP158[] = {  // CityLaser
    {SetParamType(1), "0:NORMAL 1:RENDITION", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "RANGE_LENGTH (m)", 0, 0, 0, 20.0f, 0.1f, 200.0f},
    {SetParamType(4), "TIMER (sec)", 0, 0, 0, 2.0f, 0.0f, 20.0f},
};
const SetParamDesc kP159[] = {  // CITYGADGET
    {SetParamType(2), "Type", 0, 0, 4, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "ScaleX", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "ScaleY", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "ScaleZ", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP160[] = {  // Helicopter
    {SetParamType(2), "MoveType", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "MoveParam0", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "MoveParam1", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "MoveParam2", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "MoveSec", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "PauseSec", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP162[] = {  // CITY_BOMB_SMALL
    {SetParamType(4), "Range (point)", 0, 0, 0, 50.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP164[] = {  // BK_TANK_COLI
    {SetParamType(4), "X", 0, 0, 0, 40.0f, 1.0f, 10000.0f},
    {SetParamType(4), "Y", 0, 0, 0, 40.0f, 1.0f, 10000.0f},
    {SetParamType(4), "Z", 0, 0, 0, 40.0f, 1.0f, 10000.0f},
    {SetParamType(1), "type", 0, 0, 3, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "sec", 0, 0, 0, 1.0f, 0.0f, 10000.0f},
    {SetParamType(4), "Not in Use", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
};
const SetParamDesc kP166[] = {  // FALL_HIWAY
    {SetParamType(1), "Road Type", 0, 0, 1, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP167[] = {  // FALL_LARGE
    {SetParamType(4), "Height", 0, 0, 0, 150.0f, 0.0f, 1000.0f},
};
const SetParamDesc kP171[] = {  // ELEC_LIGHT
    {SetParamType(1), "Type", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "RotateRange", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "RotateSpeed", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "LightLength", 0, 0, 0, 100.0f, 40.0f, 1000.0f},
};
const SetParamDesc kP172[] = {  // ELEC_PANEL
    {SetParamType(1), "Color", 0, 0, 3, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "Type", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "Accell", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "MoveVectorX", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "MoveVectorY", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "MoveVectorZ", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
};
const SetParamDesc kP173[] = {  // ELEC_BAR
    {SetParamType(2), "", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "scale", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "offset", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "moving second", 0, 0, 0, 5.0f, 0.0f, 65536.0f},
    {SetParamType(4), "hiding second", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "appearing ratio", 0, 0, 0, 0.1f, 0.0f, 1.0f},
    {SetParamType(4), "synchronize", 0, 0, 0, 0.0f, 0.0f, 1.0f},
    {SetParamType(1), "number of bars", 1, 1, 9, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP174[] = {  // ELEC_SECURITY
    {SetParamType(1), "type", 0, 0, 2, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "range", 0, 0, 0, 50.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP175[] = {  // ELEC_BIGBLOCK
    {SetParamType(1), "BlockType", 0, 0, 9, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "Scale X", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "Scale Y", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "Scale Z", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchRange", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "Initial Y", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(1), "CollisionFlag", 0, 0, 1, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP176[] = {  // ELEC_WALL
    {SetParamType(1), "", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "AppearAngleX", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "AppearAngleY", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
};
const SetParamDesc kP177[] = {  // ELEC_WALLSWITCH
    {SetParamType(4), "range", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP178[] = {  // ELEC_BARRIER
    {SetParamType(1), "BarrierType", 0, 0, 2, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP182[] = {  // ELEC_FAN
    {SetParamType(4), "height", 0, 0, 0, 15.0f, 0.1f, 65536.0f},
    {SetParamType(4), "radius", 0, 0, 0, 25.0f, 0.1f, 65536.0f},
    {SetParamType(4), "power", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP183[] = {  // ELEC_SPRING
    {SetParamType(4), "level", 0, 0, 0, 0.0f, 0.0f, 15.0f},
    {SetParamType(4), "nocontrol time (sec)", 0, 0, 0, 0.0f, 0.0f, 3600.0f},
};
const SetParamDesc kP184[] = {  // ELEC_FIREWALL
    {SetParamType(4), "Scale X", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "Scale Y", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "Scale Z", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchRange", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "Initial Y", 0, 0, 0, -370.0f, -65536.0f, 0.0f},
};
const SetParamDesc kP185[] = {  // ELEC_CUBE
    {SetParamType(4), "Scale", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP191[] = {  // ELEC_ROLLHEXA
    {SetParamType(4), "RotateSpeed", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
};
const SetParamDesc kP193[] = {  // ELEC_FOOTINGROTATE
    {SetParamType(2), "OBJ_NUM", 4, 1, 32, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "RADIUS m", 0, 0, 0, 20.0f, 1.0f, 65536.0f},
    {SetParamType(4), "CIRCLE_SPD deg/sec", 0, 0, 0, 0.0f, -1080.0f, 1080.0f},
};
const SetParamDesc kP195[] = {  // BombingWall
    {SetParamType(2), "Type 0:Out 1:In", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "Range (point)", 0, 0, 0, 50.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP196[] = {  // Researcher
    {SetParamType(2), "Type 0:FaceUp 1:FaceDown", 0, 0, 1, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP197[] = {  // BombServer
    {SetParamType(2), "Type 0:Bomb 1:HealUnit", 0, 0, 1, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP201[] = {  // METEOR_L
    {SetParamType(4), "RANGE m", 0, 0, 0, 50.0f, 0.0f, 65536.0f},
    {SetParamType(4), "MOVE_SPD m/s", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "DIRECTION_X deg", 0, 0, 0, 0.0f, -180.0f, 180.0f},
    {SetParamType(4), "DIRECTION_Y deg", 0, 0, 0, 0.0f, -180.0f, 180.0f},
    {SetParamType(4), "ROT_SPD_X deg/s", 0, 0, 0, 0.0f, -1080.0f, 1080.0f},
    {SetParamType(4), "ROT_SPD_Z deg/s", 0, 0, 0, 0.0f, -1080.0f, 1080.0f},
    {SetParamType(4), "ROT_SPD_Y deg/s", 0, 0, 0, 0.0f, -1080.0f, 1080.0f},
    {SetParamType(4), "LIFETIME s", 0, 0, 0, 5.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP202[] = {  // METEOR_S
    {SetParamType(4), "RANGE m", 0, 0, 0, 50.0f, 0.0f, 65536.0f},
    {SetParamType(4), "MOVE_SPD m/s", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "DIRECTION_X deg", 0, 0, 0, 0.0f, -180.0f, 180.0f},
    {SetParamType(4), "DIRECTION_Y deg", 0, 0, 0, 0.0f, -180.0f, 180.0f},
    {SetParamType(4), "ROT_SPD_X deg/s", 0, 0, 0, 0.0f, -1080.0f, 1080.0f},
    {SetParamType(4), "ROT_SPD_Z deg/s", 0, 0, 0, 0.0f, -1080.0f, 1080.0f},
    {SetParamType(4), "ROT_SPD_Y deg/s", 0, 0, 0, 0.0f, -1080.0f, 1080.0f},
    {SetParamType(4), "LIFETIME s", 0, 0, 0, 5.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP204[] = {  // ARKCANNON
    {SetParamType(2), "0:GRAND 1:AIR", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "RANGE m", 0, 0, 0, 50.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP205[] = {  // SPACEGADGET
    {SetParamType(2), "Model", 0, 0, 100, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "RotDegSpdX", 0, 0, 0, 10.0f, 0.0f, 65536.0f},
    {SetParamType(4), "RotDegSpdY", 0, 0, 0, 10.0f, 0.0f, 65536.0f},
    {SetParamType(4), "RotDegSpdZ", 0, 0, 0, 10.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP206[] = {  // GravityChangeSwitch
    {SetParamType(1), "GRAVITY", 0, 0, 5, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP207[] = {  // GravityChangeZone
    {SetParamType(1), "GRAVITY", 0, 0, 5, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP208[] = {  // GravityChangeCollision
    {SetParamType(4), "SIZE X m", 0, 0, 0, 10.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SIZE Y m", 0, 0, 0, 10.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SIZE Z m", 0, 0, 0, 10.0f, 0.0f, 65536.0f},
    {SetParamType(1), "GRAVITY", 0, 0, 5, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP210[] = {  // ArkLaser
    {SetParamType(4), "Length point", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "ShotSec", 0, 0, 0, 2.0f, 0.0f, 65536.0f},
    {SetParamType(4), "WaitSec", 0, 0, 0, 6.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP212[] = {  // FootingBreak
    {SetParamType(2), "Type 0:Burst 1:Hover", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "WaitSec", 0, 0, 0, 2.0f, 0.0f, 65536.0f},
    {SetParamType(4), "HoverLength point", 0, 0, 0, 20.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "HoverSec", 0, 0, 0, 6.0f, 0.0f, 65536.0f},
    {SetParamType(4), "MoveLengthX point", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "MoveLengthY point", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "MoveLengthZ point", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "MoveSec", 0, 0, 0, 5.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP213[] = {  // FootingRoll
    {SetParamType(2), "Model 0:Small 1:Large", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "MoveLengthX point", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "MoveLengthY point", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "MoveLengthZ point", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "MoveSec", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "MovePauseSec", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(2), "RotType 0:OneWay 1:RT", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(2), "RotAxis 0:X 1:Y 2:Z", 0, 0, 2, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "RotSpd deg/sec", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "RotMax(RT Only) deg", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP214[] = {  // SECURITY LASER
    {SetParamType(1), "model", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "length", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "rot time(sec)", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "rot Y(deg)", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "move sec", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "X", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Y", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Z", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(1), "type", 0, 0, 2, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP217[] = {  // CLOSE WALL
    {SetParamType(4), "width", 0, 0, 0, 40.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "speed", 0, 0, 0, 4.0f, -65536.0f, 65536.0f},
};
const SetParamDesc kP218[] = {  // DEFENSE WALL
    {SetParamType(4), "width", 0, 0, 0, 40.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "height", 0, 0, 0, 40.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "depth", 0, 0, 0, 40.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "speed", 0, 0, 0, 4.0f, -65536.0f, 65536.0f},
};
const SetParamDesc kP219[] = {  // POP FOOTING
    {SetParamType(1), "model", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "sec_begin", 0, 0, 0, 1.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "sec_wait", 0, 0, 0, 1.0f, -65536.0f, 65536.0f},
};
const SetParamDesc kP220[] = {  // RAIL SWITCH
    {SetParamType(1), "route", 0, 0, 65536, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP221[] = {  // BASE DOOR
    {SetParamType(1), "type", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "model", 0, 0, 2, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "width", 0, 0, 0, 100.0f, 1.0f, 10000.0f},
    {SetParamType(4), "height", 0, 0, 0, 100.0f, 1.0f, 10000.0f},
    {SetParamType(4), "depth", 0, 0, 0, 100.0f, 1.0f, 10000.0f},
    {SetParamType(4), "X", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Y", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Z", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
};
const SetParamDesc kP223[] = {  // E_P_COLI
    {SetParamType(4), "X", 0, 0, 0, 100.0f, 1.0f, 10000.0f},
    {SetParamType(4), "Y", 0, 0, 0, 100.0f, 1.0f, 10000.0f},
    {SetParamType(4), "Z", 0, 0, 0, 100.0f, 1.0f, 10000.0f},
    {SetParamType(1), "type", 0, 0, 3, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "sec", 0, 0, 0, 1.0f, 0.0f, 10000.0f},
    {SetParamType(4), "Not in Use", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
};
const SetParamDesc kP224[] = {  // PLANE RAIL
    {SetParamType(4), "dist", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "speed", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP225[] = {  // WATCH CAMERA
    {SetParamType(4), "posX", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "posY", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "posZ", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "angX", 0, 0, 0, 0.0f, 0.0f, 360.0f},
    {SetParamType(4), "angY", 0, 0, 0, 0.0f, 0.0f, 360.0f},
    {SetParamType(4), "angZ", 0, 0, 0, 0.0f, 0.0f, 360.0f},
    {SetParamType(4), "width", 0, 0, 0, 10.0f, 0.0f, 65536.0f},
    {SetParamType(4), "height", 0, 0, 0, 10.0f, 0.0f, 65536.0f},
    {SetParamType(4), "depth", 0, 0, 0, 10.0f, 0.0f, 65536.0f},
    {SetParamType(4), "lookPosX", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "lookPosY", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "lookPosZ", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "lookAngX", 0, 0, 0, 0.0f, 0.0f, 360.0f},
    {SetParamType(4), "lookAngY", 0, 0, 0, 0.0f, 0.0f, 360.0f},
    {SetParamType(4), "lookAngZ", 0, 0, 0, 0.0f, 0.0f, 360.0f},
};
const SetParamDesc kP226[] = {  // MAGMA
    {SetParamType(1), "model", 0, 0, 9, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "Y", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "speed", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP227[] = {  // BA Shield
    {SetParamType(1), "type", 0, 0, 2, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP228[] = {  // BD Hologram
    {SetParamType(4), "distance", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(1), "voice id", 0, 0, 65536, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP230[] = {  // BA Mine
    {SetParamType(4), "X", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Y", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Z", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "second", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP232[] = {  // BA GUNSHIP
    {SetParamType(4), "radius", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "height", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "second", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(1), "attack", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "N/A", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(1), "ComId", -1, -1, 255, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "num", 0, 0, 65536, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "delay", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "interval", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP236[] = {  // GUN_SOLDIER
    {SetParamType(4), "MoveRange", 0, 0, 0, 200.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchRange", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchAngle", 0, 0, 0, 0.0f, -360.0f, 360.0f},
    {SetParamType(4), "SearchWidth", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeight", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeightOffset", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "MoveSpeedRatio", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(1), "HaveShield", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "WeaponType", 0, 0, 6, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "AppearType", 0, 0, 5, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "Pos0_WaitType", 0, 0, 3, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "Pos0_WaitSec", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "Pos0_MoveSpeedRatio", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "Pos1_X", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Pos1_Z", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(1), "Pos1_WaitType", 0, 0, 3, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "Pos1_WaitSec", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "Pos1_MoveSpeedRatio", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "Pos2_X", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Pos2_Z", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(1), "Pos2_WaitType", 0, 0, 3, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "Pos2_WaitSec", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "Pos2_MoveSpeedRatio", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP237[] = {  // GUN_BEETLE
    {SetParamType(4), "MoveRange", 0, 0, 0, 200.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchRange", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchAngle", 0, 0, 0, 0.0f, -360.0f, 360.0f},
    {SetParamType(4), "SearchWidth", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeight", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeightOffset", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "MoveSpeedRatio", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(1), "AppearType", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "ActionType", 0, 0, 2, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "", 0, 0, 8, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "FloatWidth", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "AttackStart", 0, 0, 0, 0.4f, 0.0f, 1.0f},
    {SetParamType(4), "AttackEnd", 0, 0, 0, 0.6f, 0.0f, 1.0f},
    {SetParamType(1), "PathMirror", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "BodyType", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "WeaponType", 0, 0, 4, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "SparkDischarge", 0, 0, 0, 2.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SparkWait", 0, 0, 0, 2.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP238[] = {  // GUN_BIGFOOT
    {SetParamType(4), "MoveRange", 0, 0, 0, 200.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchRange", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchAngle", 0, 0, 0, 0.0f, -360.0f, 360.0f},
    {SetParamType(4), "SearchWidth", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeight", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeightOffset", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "MoveSpeedRatio", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(1), "AppearType", 0, 0, 4, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "WeaponType", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "OffsetPos_Y", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP239[] = {  // GUN_ROBOT
    {SetParamType(4), "MoveRange", 0, 0, 0, 200.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchRange", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchAngle", 0, 0, 0, 0.0f, -360.0f, 360.0f},
    {SetParamType(4), "SearchWidth", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeight", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeightOffset", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "MoveSpeedRatio", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(1), "AppearType", 0, 0, 3, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "WeaponType", 0, 0, 5, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "BodyType", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "OffsetPos_X", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "OffsetPos_Y", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "OffsetPos_Z", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(1), "WaitActMoveType", 0, 0, 3, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "Pos0_ActionTime", 0, 0, 0, 3.0f, 0.0f, 65536.0f},
    {SetParamType(1), "Pos0_ActionType", 0, 0, 2, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "Pos0_MoveSpeedRatio", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "Pos1_X", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Pos1_Z", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Pos1_ActionTime", 0, 0, 0, 3.0f, 0.0f, 65536.0f},
    {SetParamType(1), "Pos1_ActionType", 0, 0, 2, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "Pos1_MoveSpeedRatio", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "Pos2_X", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Pos2_Z", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Pos2_ActionTime", 0, 0, 0, 3.0f, 0.0f, 65536.0f},
    {SetParamType(1), "Pos2_ActionType", 0, 0, 2, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "Pos2_MoveSpeedRatio", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP240[] = {  // BK_GIANT
    {SetParamType(4), "MoveRange", 0, 0, 0, 200.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchRange", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchAngle", 0, 0, 0, 0.0f, -360.0f, 360.0f},
    {SetParamType(4), "SearchWidth", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeight", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeightOffset", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "MoveSpeedRatio", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(1), "AppearType", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "WeaponType", 0, 0, 2, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "OffsetPos_Y", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(1), "Gurad : ON", 1, 0, 1, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP241[] = {  // BK_SOLDIER
    {SetParamType(4), "MoveRange", 0, 0, 0, 200.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchRange", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchAngle", 0, 0, 0, 0.0f, -360.0f, 360.0f},
    {SetParamType(4), "SearchWidth", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeight", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeightOffset", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "MoveSpeedRatio", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(1), "HaveShield", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "WeaponType", 0, 0, 8, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "AppearType", 0, 0, 5, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "Pos0_WaitType", 0, 0, 2, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "Pos0_WaitSec", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "Pos0_MoveSpeedRatio", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "Pos1_X", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Pos1_Z", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(1), "Pos1_WaitType", 0, 0, 2, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "Pos1_WaitSec", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "Pos1_MoveSpeedRatio", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "Pos2_X", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Pos2_Z", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(1), "Pos2_WaitType", 0, 0, 2, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "Pos2_WaitSec", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "Pos2_MoveSpeedRatio", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(1), "RideAirSaucer", 0, 0, 1, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP242[] = {  // BK_WINGLARGE
    {SetParamType(4), "MoveRange", 0, 0, 0, 200.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchRange", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchAngle", 0, 0, 0, 0.0f, -360.0f, 360.0f},
    {SetParamType(4), "SearchWidth", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeight", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeightOffset", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "MoveSpeedRatio", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(1), "AppearType", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "ActionType", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "", 0, 0, 8, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "FloatWidth", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "AttackStart", 0, 0, 0, 0.4f, 0.0f, 1.0f},
    {SetParamType(4), "AttackEnd", 0, 0, 0, 0.6f, 0.0f, 1.0f},
    {SetParamType(1), "PathMirror", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(3), "Type", 0, 0, 17, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP243[] = {  // BK_WINGSMALL
    {SetParamType(4), "MoveRange", 0, 0, 0, 200.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchRange", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchAngle", 0, 0, 0, 0.0f, -360.0f, 360.0f},
    {SetParamType(4), "SearchWidth", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeight", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeightOffset", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "MoveSpeedRatio", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(1), "AppearType", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "ActionType", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "", 0, 0, 8, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "FloatWidth", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "AttackStart", 0, 0, 0, 0.4f, 0.0f, 1.0f},
    {SetParamType(4), "AttackEnd", 0, 0, 0, 0.6f, 0.0f, 1.0f},
    {SetParamType(1), "PathMirror", 0, 0, 1, 0.0f, 0.0f, 0.0f},
};
const SetParamDesc kP244[] = {  // BK_WORM
    {SetParamType(4), "MoveRange", 0, 0, 0, 200.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchRange", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchAngle", 0, 0, 0, 0.0f, -360.0f, 360.0f},
    {SetParamType(4), "SearchWidth", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeight", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeightOffset", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "MoveSpeedRatio", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(1), "WeaponType", 0, 0, 2, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "AttackTimes", 1, 1, 100, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "IntervalSec", 0, 0, 0, 3.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP245[] = {  // BK_LARVA
    {SetParamType(4), "MoveRange", 0, 0, 0, 200.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchRange", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchAngle", 0, 0, 0, 0.0f, -360.0f, 360.0f},
    {SetParamType(4), "SearchWidth", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeight", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeightOffset", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "MoveSpeedRatio", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(1), "Num", 10, 1, 100, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "AppearRange", 0, 0, 0, 30.0f, 0.0f, 65536.0f},
    {SetParamType(1), "AppearType", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "Offset_Y", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
};
const SetParamDesc kP246[] = {  // BK_CHAOS
    {SetParamType(4), "MoveRange", 0, 0, 0, 200.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchRange", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchAngle", 0, 0, 0, 0.0f, -360.0f, 360.0f},
    {SetParamType(4), "SearchWidth", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeight", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeightOffset", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "MaxLife", 0, 0, 0, 20.0f, 1.0f, 65536.0f},
    {SetParamType(1), "ShapeType", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "ChibiNum", 2, 2, 65536, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "MoveHeight", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "MoveHeightOffset", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "CombineStartTime", 0, 0, 0, 1.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "CombineTime", 0, 0, 0, 1.0f, 0.1f, 65536.0f},
};
const SetParamDesc kP247[] = {  // BK_NINJA
    {SetParamType(4), "MoveRange", 0, 0, 0, 200.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchRange", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchAngle", 0, 0, 0, 0.0f, -360.0f, 360.0f},
    {SetParamType(4), "SearchWidth", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeight", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeightOffset", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "MoveSpeedRatio", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(1), "AppearType", 0, 0, 3, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "ShootCount", 1, 1, 65536, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "AttackInterval", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "WaitInterval", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "Pos0_X", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Pos0_Y", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Pos0_Z", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Pos0_AngY", 0, 0, 0, 0.0f, -180.0f, 180.0f},
    {SetParamType(1), "Pos0_WaitType", 0, 0, 3, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "Pos0_DisappearTime", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "Pos1_X", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Pos1_Y", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Pos1_Z", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Pos1_AngY", 0, 0, 0, 0.0f, -180.0f, 180.0f},
    {SetParamType(1), "Pos1_WaitType", 0, 0, 3, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "Pos1_DisappearTime", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP248[] = {  // EGG_PAWN
    {SetParamType(4), "MoveRange", 0, 0, 0, 200.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchRange", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchAngle", 0, 0, 0, 0.0f, -360.0f, 360.0f},
    {SetParamType(4), "SearchWidth", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeight", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeightOffset", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "MoveSpeedRatio", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(1), "HaveShield", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "WeaponType", 0, 0, 3, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "AppearType", 0, 0, 3, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "OffsetPos_X", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "OffsetPos_Z", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "OffsetPos_Y", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(1), "WaitActMoveType", 0, 0, 3, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "Pos0_ActionTime", 0, 0, 0, 3.0f, 0.0f, 65536.0f},
    {SetParamType(1), "Pos0_ActionType", 0, 0, 2, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "Pos0_MoveSpeedRatio", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "Pos1_X", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Pos1_Z", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Pos1_ActionTime", 0, 0, 0, 3.0f, 0.0f, 65536.0f},
    {SetParamType(1), "Pos1_ActionType", 0, 0, 2, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "Pos1_MoveSpeedRatio", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(4), "Pos2_X", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Pos2_Z", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "Pos2_ActionTime", 0, 0, 0, 3.0f, 0.0f, 65536.0f},
    {SetParamType(1), "Pos2_ActionType", 0, 0, 2, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "Pos2_MoveSpeedRatio", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
};
const SetParamDesc kP249[] = {  // EGG_PIERROT
    {SetParamType(4), "MoveRange", 0, 0, 0, 200.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchRange", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchAngle", 0, 0, 0, 0.0f, -360.0f, 360.0f},
    {SetParamType(4), "SearchWidth", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeight", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeightOffset", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "MoveSpeedRatio", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(1), "AppearType", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(1), "NOT_USE", 0, 0, 0, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "BakudanTime", 0, 0, 0, 5.0f, 0.0f, 65536.0f},
    {SetParamType(4), "OffsetPos_X", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "OffsetPos_Y", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "OffsetPos_Z", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
};
const SetParamDesc kP250[] = {  // EGG_SHADOWANDROID
    {SetParamType(4), "MoveRange", 0, 0, 0, 200.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchRange", 0, 0, 0, 0.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchAngle", 0, 0, 0, 0.0f, -360.0f, 360.0f},
    {SetParamType(4), "SearchWidth", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeight", 0, 0, 0, 100.0f, 0.0f, 65536.0f},
    {SetParamType(4), "SearchHeightOffset", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "MoveSpeedRatio", 0, 0, 0, 1.0f, 0.0f, 65536.0f},
    {SetParamType(1), "AppearType", 0, 0, 1, 0.0f, 0.0f, 0.0f},
    {SetParamType(4), "OffsetPos_X", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "OffsetPos_Y", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
    {SetParamType(4), "OffsetPos_Z", 0, 0, 0, 0.0f, -65536.0f, 65536.0f},
};
}  // namespace

const std::vector<SetObjDesc>& OriginalSetCatalog() {
    static const std::vector<SetObjDesc> k = {
        {"GadgetCommonDataStart", 0x2580, 1, 0x8052C0E8, 0x00000000, nullptr, 0},
        {"Sample", 0x2586, 1, 0x8055A2D8, 0x802DFBAC, kP1, 16},
        {"CONTAINER", 0x0009, 1, 0x80526590, 0x800F6A38, kP2, 3},
        {"HRD_CONTAINER", 0x000A, 1, 0x80526778, 0x800F9B28, kP3, 3},
        {"UNBRK_CONTAINER", 0x000B, 1, 0x805268C4, 0x800FC17C, kP4, 1},
        {"WEAPON_CONTAINER", 0x000C, 1, 0x805269C4, 0x800FCE70, kP5, 2},
        {"SECRET CONTAINER", 0x003A, 1, 0x8054E84C, 0x8027850C, kP6, 1},
        {"BALLOON", 0x0013, 1, 0x80525828, 0x800E6E54, kP7, 7},
        {"SPRING", 0x0001, 1, 0x805289B8, 0x80120554, kP8, 2},
        {"DASHPANEL", 0x0003, 1, 0x80526B34, 0x800FF3D8, kP9, 2},
        {"JUMP_BOARD", 0x0004, 1, 0x805278A4, 0x8010E8FC, kP10, 3},
        {"RING", 0x0010, 1, 0x80527D04, 0x80112738, kP11, 5},
        {"LONGSPRING", 0x0002, 1, 0x8052798C, 0x8010F8F0, kP12, 2},
        {"SAVEPOINT", 0x0005, 1, 0x80527FC0, 0x801177D8, kP13, 1},
        {"WEIGHT", 0x0019, 1, 0x80529464, 0x8012AFB0, kP14, 9},
        {"GOALRING", 0x0014, 1, 0x805272CC, 0x801066B4, kP15, 1},
        {"SWITCH", 0x0015, 1, 0x80528C60, 0x801234E8, kP16, 1},
        {"DASHRING", 0x0006, 1, 0x80526C1C, 0x80100580, kP17, 2},
        {"TARGETSWITCH", 0x0016, 1, 0x80528E2C, 0x80124984, kP18, 6},
        {"BOMB", 0x000D, 1, 0x80525D98, 0x800EE11C, nullptr, 0},
        {"FAN", 0x001A, 1, 0x80526F44, 0x80102688, kP20, 10},
        {"SECRETKEY", 0x001D, 1, 0x805282EC, 0x8011C318, nullptr, 0},
        {"SECRETDOOR", 0x001E, 1, 0x80528278, 0x8011B9B8, nullptr, 0},
        {"BREAK_BLAST", 0x001C, 1, 0x80525B14, 0x800ECD2C, nullptr, 0},
        {"BRK_OBJ", 0x001B, 1, 0x80525FB0, 0x800F1734, kP24, 1},
        {"CAGE", 0x0007, 1, 0x805260EC, 0x800F25B4, kP25, 4},
        {"CAPTURE_CAGE", 0x0037, 1, 0x80526238, 0x800F386C, kP26, 3},
        {"HINTRING", 0x0011, 1, 0x805275B0, 0x80109D58, kP27, 5},
        {"UD_REEL", 0x0008, 1, 0x805290E0, 0x80127784, kP28, 4},
        {"ITEM_BOX", 0x0012, 1, 0x805276D0, 0x8010BF50, kP29, 1},
        {"", 0x0018, 4, 0x80525960, 0x00000000, nullptr, 0},
        {"", 0x0039, 4, 0x80525A40, 0x00000000, nullptr, 0},
        {"FIRE", 0x0034, 1, 0x805270C4, 0x801043C8, kP32, 3},
        {"ENERGY_CORE", 0x0033, 1, 0x80526CDC, 0x80101538, kP33, 1},
        {"POISON_GAS", 0x0035, 1, 0x80527AE4, 0x80110BA4, kP34, 3},
        {"WARP_HOLE", 0x001F, 1, 0x805291FC, 0x80129840, nullptr, 0},
        {"ROCKET", 0x000E, 1, 0x80527E6C, 0x80114CC4, kP36, 2},
        {"SET_VEHICLE", 0x004F, 1, 0x80528790, 0x8011E508, kP37, 1},
        {"SET_WEAPON", 0x0020, 1, 0x80528854, 0x8011F010, kP38, 1},
        {"SET_CHARACTOR", 0x0190, 1, 0x80528138, 0x80119E0C, kP39, 2},
        {"BlockChange", 0x0059, 1, 0x80525CF4, 0x800EDD74, kP40, 7},
        {"CATCHSTICK", 0x005A, 1, 0x80526398, 0x800F4EEC, kP41, 1},
        {"PARTICLE", 0x258A, 1, 0x805286D8, 0x8011E024, kP42, 4},
        {"HEALING_UNIT", 0x0038, 1, 0x80527354, 0x801077F4, nullptr, 0},
        {"SETCOLLISION", 0x0050, 1, 0x80528560, 0x8011D038, kP44, 7},
        {"Fruit", 0x0022, 1, 0x805271C4, 0x801056F4, nullptr, 0},
        {"LIGHT_COLI", 0x0062, 1, 0x8053F168, 0x801EF2B0, kP46, 9},
        {"HINT COLLISION", 0x0051, 1, 0x805451B4, 0x802079A4, kP47, 10},
        {"DebugDebugMissionClearCollision", 0x2592, 1, 0x80558D5C, 0x802C8D20, kP48, 1},
        {"DARKSPINENTRANCE", 0x0061, 1, 0x8054AFE0, 0x80258BE0, kP49, 1},
        {"SET GENERATOR", 0x2593, 1, 0x8054EEC0, 0x8027C308, kP50, 5},
        {"MissionClearCollision", 0x2595, 1, 0x805481F4, 0x80231C58, kP51, 2},
        {"HINT CONTROLLER", 0x2596, 1, 0x8055B0C8, 0x802F330C, nullptr, 0},
        {"TANK", 0x0021, 1, 0x80528F50, 0x8012590C, kP53, 2},
        {"SET_SE_LOOP", 0x2597, 1, 0x8055E960, 0x8033DC70, kP54, 7},
        {"SET_SE_ONESHOT", 0x2598, 1, 0x8055EB90, 0x8033E41C, kP55, 6},
        {"GadgetCommonDataEnd", 0x2581, 1, 0x8052C10C, 0x00000000, nullptr, 0},
        {"WeaponDataStart", 0x2584, 1, 0x8051FA88, 0x00000000, nullptr, 0},
        {"", 0x00C8, 4, 0x8051FC88, 0x00000000, nullptr, 0},
        {"", 0x00C9, 4, 0x80520930, 0x00000000, nullptr, 0},
        {"", 0x00CA, 4, 0x8051F698, 0x00000000, nullptr, 0},
        {"", 0x00CB, 4, 0x8051F530, 0x00000000, nullptr, 0},
        {"", 0x00CC, 4, 0x80520A98, 0x00000000, nullptr, 0},
        {"", 0x00CE, 4, 0x80542F60, 0x00000000, nullptr, 0},
        {"", 0x00CF, 4, 0x8051FD58, 0x00000000, nullptr, 0},
        {"", 0x00D0, 4, 0x8051FAD0, 0x00000000, nullptr, 0},
        {"", 0x00D1, 4, 0x8051FEC8, 0x00000000, nullptr, 0},
        {"", 0x00D2, 4, 0x8055AF68, 0x00000000, nullptr, 0},
        {"", 0x00DC, 4, 0x8051FB88, 0x00000000, nullptr, 0},
        {"", 0x00DD, 4, 0x8051F780, 0x00000000, nullptr, 0},
        {"", 0x00DE, 4, 0x805209E8, 0x00000000, nullptr, 0},
        {"", 0x00DF, 4, 0x8051F8E0, 0x00000000, nullptr, 0},
        {"", 0x00E0, 4, 0x8051F830, 0x00000000, nullptr, 0},
        {"", 0x00E1, 4, 0x80542EB0, 0x00000000, nullptr, 0},
        {"", 0x00E6, 4, 0x8051F5E8, 0x00000000, nullptr, 0},
        {"", 0x00E7, 4, 0x8051FFA4, 0x00000000, nullptr, 0},
        {"", 0x00E8, 4, 0x8051FFF8, 0x00000000, nullptr, 0},
        {"", 0x00E9, 4, 0x8054E19C, 0x00000000, nullptr, 0},
        {"", 0x00EA, 4, 0x8054E1F0, 0x00000000, nullptr, 0},
        {"", 0x00EB, 4, 0x8054E244, 0x00000000, nullptr, 0},
        {"", 0x00F0, 4, 0x80547660, 0x00000000, nullptr, 0},
        {"", 0x00F1, 4, 0x80547248, 0x00000000, nullptr, 0},
        {"", 0x00F2, 4, 0x80547588, 0x00000000, nullptr, 0},
        {"", 0x00F3, 4, 0x805474B0, 0x00000000, nullptr, 0},
        {"", 0x00FA, 4, 0x805200E4, 0x00000000, nullptr, 0},
        {"", 0x00FB, 4, 0x8051F990, 0x00000000, nullptr, 0},
        {"", 0x00FC, 4, 0x8055AEB8, 0x00000000, nullptr, 0},
        {"", 0x00FD, 4, 0x80520138, 0x00000000, nullptr, 0},
        {"WeaponDataEnd", 0x2585, 1, 0x8051FAAC, 0x00000000, nullptr, 0},
        {"GadgetStageDataStart", 0x2582, 1, 0x8052C798, 0x00000000, nullptr, 0},
        {"STICK", 0x012C, 1, 0x80528B30, 0x80121E94, kP90, 2},
        {"TURNOVER", 0x0023, 1, 0x80528F2C, 0x801259A0, kP91, 2},
        {"ART WORK", 0x2588, 1, 0x805255B0, 0x800E5E70, kP92, 4},
        {"ART WORK ZONE", 0x2590, 1, 0x805255D4, 0x800E5DE0, kP93, 4},
        {"ART GADGET", 0x2589, 1, 0x80525460, 0x800E4360, kP94, 1},
        {"ART GADGET ZONE", 0x2591, 1, 0x80525484, 0x800E42D0, kP95, 1},
        {"FOOTING", 0x1130, 1, 0x8052AE88, 0x801496EC, kP96, 1},
        {"MOVE_FOOTING", 0x000F, 1, 0x8052B1D0, 0x80149C40, kP97, 10},
        {"ELEVATOR", 0x1132, 1, 0x8052ADD0, 0x80147EBC, kP98, 4},
        {"DOOR", 0x1133, 1, 0x8052AAF4, 0x80144360, kP99, 8},
        {"DAMAGE BLOCK", 0x1134, 1, 0x8052A918, 0x80143430, kP100, 1},
        {"FAN STAGE", 0x2594, 1, 0x80526F68, 0x80102600, kP101, 10},
        {"", 0x00FE, 4, 0x8052018C, 0x00000000, nullptr, 0},
        {"", 0x00FF, 4, 0x805201E0, 0x00000000, nullptr, 0},
        {"", 0x0100, 4, 0x80520234, 0x00000000, nullptr, 0},
        {"", 0x0101, 4, 0x80520288, 0x00000000, nullptr, 0},
        {"", 0x0102, 4, 0x80548E20, 0x00000000, nullptr, 0},
        {"", 0x0103, 4, 0x805202DC, 0x00000000, nullptr, 0},
        {"", 0x0104, 4, 0x80520330, 0x00000000, nullptr, 0},
        {"", 0x0105, 4, 0x80520384, 0x00000000, nullptr, 0},
        {"", 0x0106, 4, 0x805203D8, 0x00000000, nullptr, 0},
        {"", 0x0107, 4, 0x8052042C, 0x00000000, nullptr, 0},
        {"", 0x0108, 4, 0x80520480, 0x00000000, nullptr, 0},
        {"", 0x0109, 4, 0x805204D4, 0x00000000, nullptr, 0},
        {"", 0x010B, 4, 0x80520528, 0x00000000, nullptr, 0},
        {"", 0x010C, 4, 0x8052057C, 0x00000000, nullptr, 0},
        {"", 0x010D, 4, 0x805205D0, 0x00000000, nullptr, 0},
        {"", 0x010E, 4, 0x80520624, 0x00000000, nullptr, 0},
        {"", 0x010F, 4, 0x80520678, 0x00000000, nullptr, 0},
        {"", 0x0110, 4, 0x805206CC, 0x00000000, nullptr, 0},
        {"", 0x0111, 4, 0x80520720, 0x00000000, nullptr, 0},
        {"", 0x0112, 4, 0x80520774, 0x00000000, nullptr, 0},
        {"", 0x0113, 4, 0x805207C8, 0x00000000, nullptr, 0},
        {"", 0x0114, 4, 0x8052081C, 0x00000000, nullptr, 0},
        {"FIRE_VINE", 0x1131, 1, 0x8052B5B4, 0x8014F1AC, kP124, 3},
        {"BREAKWALL", 0x1135, 1, 0x8052A654, 0x8014065C, kP125, 1},
        {"NOBI_KUSA", 0x1137, 1, 0x8052B410, 0x8014C0F8, kP126, 5},
        {"CATAPULT", 0x1138, 1, 0x8052A864, 0x8014211C, kP127, 6},
        {"EGG_BALLOON", 0x1450, 1, 0x8052AC14, 0x00000000, nullptr, 0},
        {"E_B_COLI", 0x1451, 1, 0x8054DF5C, 0x80273848, kP129, 6},
        {"SECRET DISK", 0x1453, 1, 0x8055B6C4, 0x802FA360, nullptr, 0},
        {"TORNADO", 0x0834, 1, 0x80524F28, 0x800DE7C4, kP131, 10},
        {"TORNADO_COLLI", 0x0835, 1, 0x80525070, 0x800DFCAC, kP132, 1},
        {"ROLL_CIRCLE", 0x0836, 1, 0x8052460C, 0x800D63E0, kP133, 7},
        {"STONE_POLE", 0x0837, 1, 0x8052495C, 0x800D8208, kP134, 11},
        {"STONE_STATUE", 0x0838, 1, 0x80524D00, 0x800DD994, kP135, 4},
        {"POWER_DEVICE_CAGE", 0x0839, 1, 0x805241B0, 0x800D37EC, kP136, 1},
        {"EggFleet", 0x1069, 1, 0x80523FB0, 0x800CC3B0, kP137, 6},
        {"POWER_DEVICE_NAKED", 0x106C, 1, 0x805242E8, 0x800D4D48, kP138, 1},
        {"RainEffect", 0x106D, 1, 0x805243F8, 0x800D5584, kP139, 3},
        {"TESTNAKAZAWA", 0x2587, 1, 0x8055A318, 0x802DFC08, nullptr, 0},
        {"CIRCUS_BALL", 0x0C80, 1, 0x80529864, 0x8012FA80, kP141, 4},
        {"FIRE_RING", 0x0C85, 1, 0x80529C94, 0x80135688, nullptr, 0},
        {"Cream", 0x0BBD, 1, 0x80529BD0, 0x80134BCC, nullptr, 0},
        {"Chao", 0x0BBE, 1, 0x805296F8, 0x8012E210, kP144, 3},
        {"Monster", 0x0BC7, 1, 0x80529F0C, 0x8013962C, kP145, 4},
        {"MonsterControl", 0x0BC8, 1, 0x8052A0BC, 0x8013A920, kP146, 4},
        {"GiantLantern", 0x0BC9, 1, 0x80548A50, 0x8023703C, nullptr, 0},
        {"Coaster", 0x0C88, 1, 0x80529ACC, 0x80132F4C, kP148, 5},
        {"ThreatObj", 0x0BBC, 1, 0x8052A524, 0x8013F5E8, kP149, 2},
        {"PARK_BALLOON", 0x0C82, 1, 0x8052A2D8, 0x8013B250, kP150, 9},
        {"SHOOTING_PANEL", 0x0C83, 1, 0x8052A41C, 0x8013DCA4, kP151, 1},
        {"GONG", 0x0C81, 1, 0x80529DB4, 0x80136EA0, kP152, 1},
        {"CandleStick", 0x0BBB, 1, 0x805295D0, 0x8012D9E4, kP153, 1},
        {"CIRCUS_POLE", 0x0C87, 1, 0x80529924, 0x80130B64, kP154, 1},
        {"MORPHDOOR", 0x0C89, 1, 0x8052AB24, 0x80143874, kP155, 8},
        {"CityChaosEmerald", 0x03E8, 1, 0x805250BC, 0x800E0160, nullptr, 0},
        {"FallBuilding", 0x03E9, 1, 0x805252F8, 0x800E2CAC, kP157, 1},
        {"CityLaser", 0x03EA, 1, 0x805251C0, 0x800E0D04, kP158, 3},
        {"CITYGADGET", 0x0FA4, 1, 0x8055B41C, 0x802F74A8, kP159, 4},
        {"Helicopter", 0x0FA2, 1, 0x8055B610, 0x802F8AB4, kP160, 6},
        {"CITY_BOMB_BIG", 0x0FA0, 1, 0x8055B178, 0x802F3CE0, nullptr, 0},
        {"CITY_BOMB_SMALL", 0x0FA1, 1, 0x8055B288, 0x802F5860, kP162, 1},
        {"BK_TANK", 0x0898, 1, 0x8055D600, 0x00000000, nullptr, 0},
        {"BK_TANK_COLI", 0x0899, 1, 0x8055D8A8, 0x8032253C, kP164, 6},
        {"GUN_BUILDING", 0x089B, 1, 0x8055E1D4, 0x8032C3BC, nullptr, 0},
        {"FALL_HIWAY", 0x089A, 1, 0x8055E160, 0x8032B52C, kP166, 1},
        {"FALL_LARGE", 0x089C, 1, 0x8055E090, 0x8032AD30, kP167, 1},
        {"ELEC_CIRCUIT", 0x07D0, 1, 0x805433C8, 0x801F7BC8, nullptr, 0},
        {"ELEC_ENTRANCE", 0x07E0, 1, 0x80543478, 0x801F8034, nullptr, 0},
        {"ELEC_EXIT", 0x07EA, 1, 0x80558C08, 0x802C8600, nullptr, 0},
        {"ELEC_LIGHT", 0x07D1, 1, 0x8052B9DC, 0x80153888, kP171, 4},
        {"ELEC_PANEL", 0x07D2, 1, 0x8054B238, 0x8025977C, kP172, 6},
        {"ELEC_BAR", 0x07D3, 1, 0x8052B808, 0x801527C0, kP173, 8},
        {"ELEC_SECURITY", 0x07D4, 1, 0x8052BC10, 0x80157F94, kP174, 2},
        {"ELEC_BIGBLOCK", 0x07D5, 1, 0x8052BDE0, 0x80158A10, kP175, 7},
        {"ELEC_WALL", 0x07D7, 1, 0x805435CC, 0x801F8F94, kP176, 3},
        {"ELEC_WALLSWITCH", 0x07E1, 1, 0x80543680, 0x801FA2AC, kP177, 1},
        {"ELEC_BARRIER", 0x07D8, 1, 0x8054D050, 0x80263BC0, kP178, 1},
        {"ELEC_CORE", 0x07DB, 1, 0x8054309C, 0x801F47A8, nullptr, 0},
        {"ELEC_BOMB", 0x07DC, 1, 0x8054D0C4, 0x802642A8, nullptr, 0},
        {"ELEC_ACCESS", 0x07DD, 1, 0x80549C78, 0x80248D10, nullptr, 0},
        {"ELEC_FAN", 0x07DA, 1, 0x8054D2C8, 0x80266AA4, kP182, 3},
        {"ELEC_SPRING", 0x07DE, 1, 0x8052BF08, 0x801593A4, kP183, 2},
        {"ELEC_FIREWALL", 0x07DF, 1, 0x80543320, 0x801F68EC, kP184, 5},
        {"ELEC_CUBE", 0x07E2, 1, 0x80546A48, 0x8021C074, kP185, 1},
        {"ELEC_SMALLCUBE", 0x07E4, 1, 0x80546994, 0x8021B0C0, nullptr, 0},
        {"ELEC_PILLAR", 0x07E3, 1, 0x80546AB0, 0x8021C930, nullptr, 0},
        {"ELEC_SMALLPILLAR", 0x07E7, 1, 0x805480A0, 0x8023131C, nullptr, 0},
        {"ELEC_WAKKA", 0x07E5, 1, 0x80548108, 0x802316C4, nullptr, 0},
        {"ELEC_KYUU", 0x084A, 1, 0x8054803C, 0x802308C0, nullptr, 0},
        {"ELEC_ROLLHEXA", 0x07E8, 1, 0x8054D3B4, 0x802674D4, kP191, 1},
        {"ELEC_COREWALL", 0x07E9, 1, 0x8054D18C, 0x80264B54, nullptr, 0},
        {"ELEC_FOOTINGROTATE", 0x07EB, 1, 0x80559F68, 0x802DD78C, kP193, 3},
        {"ELEC_CIRCUITCOLLI", 0x07EC, 1, 0x8055E740, 0x8033C854, nullptr, 0},
        {"BombingWall", 0x1004, 1, 0x8055CFFC, 0x803164E4, kP195, 2},
        {"Researcher", 0x1005, 1, 0x8055D2FC, 0x8031A3AC, kP196, 1},
        {"BombServer", 0x1006, 1, 0x8055D0BC, 0x80316EA4, kP197, 1},
        {"GunLift", 0x1518, 4, 0x8055D174, 0x00000000, nullptr, 0},
        {"DEFENSE_SYSTEM", 0x1388, 1, 0x8054743C, 0x80224738, nullptr, 0},
        {"DEFENSE_SHIELD", 0x1389, 1, 0x805473A4, 0x8022332C, nullptr, 0},
        {"METEOR_L", 0x138A, 1, 0x80546CD4, 0x8021D65C, kP201, 8},
        {"METEOR_S", 0x138B, 1, 0x80546F48, 0x8021E4B0, kP202, 8},
        {"GRINDGADGET", 0x138D, 1, 0x80547808, 0x80228674, nullptr, 0},
        {"ARKCANNON", 0x138E, 1, 0x805477A4, 0x802280E4, kP204, 2},
        {"SPACEGADGET", 0x1392, 1, 0x8054D834, 0x8026B500, kP205, 4},
        {"GravityChangeSwitch", 0x14B4, 1, 0x80549A0C, 0x80247104, kP206, 1},
        {"GravityChangeZone", 0x14B5, 1, 0x80549BFC, 0x802482B8, kP207, 1},
        {"GravityChangeCollision", 0x14B6, 1, 0x80549B38, 0x80247C24, kP208, 4},
        {"GravitySignBoard", 0x14B7, 1, 0x8054B048, 0x80259400, nullptr, 0},
        {"ArkLaser", 0x14BE, 1, 0x8054DCB0, 0x8026E7A0, kP210, 3},
        {"BACKDROP", 0x189C, 1, 0x8054D898, 0x8026B938, nullptr, 0},
        {"FootingBreak", 0x189E, 1, 0x8054CF40, 0x8026318C, kP212, 8},
        {"FootingRoll", 0x189F, 1, 0x8054CD2C, 0x802619F4, kP213, 10},
        {"SECURITY LASER", 0x13EF, 1, 0x80547EF4, 0x8022C7C0, kP214, 9},
        {"SUPER COMPUTER", 0x1771, 1, 0x80547FAC, 0x8022DD1C, nullptr, 0},
        {"MAGMA GUARD", 0x1838, 1, 0x80547BA4, 0x8022B0A0, nullptr, 0},
        {"CLOSE WALL", 0x1773, 1, 0x805479D0, 0x80228D5C, kP217, 2},
        {"DEFENSE WALL", 0x1772, 1, 0x80547B30, 0x80229A8C, kP218, 4},
        {"POP FOOTING", 0x13F0, 1, 0x80547CA8, 0x8022BFAC, kP219, 3},
        {"RAIL SWITCH", 0x13ED, 1, 0x8054AF2C, 0x80257D34, kP220, 1},
        {"BASE DOOR", 0x13F1, 1, 0x8054AE4C, 0x802569F4, kP221, 8},
        {"ESCAPE_PLANE", 0x13EC, 1, 0x8054AC30, 0x00000000, nullptr, 0},
        {"E_P_COLI", 0x13F2, 1, 0x8054C918, 0x8025E500, kP223, 6},
        {"PLANE RAIL", 0x13F3, 1, 0x80555820, 0x802ABEA0, kP224, 2},
        {"WATCH CAMERA", 0x1770, 1, 0x8054D6B0, 0x80268128, kP225, 15},
        {"MAGMA", 0x1839, 1, 0x8054ED68, 0x8027BD00, kP226, 3},
        {"BA Shield", 0x1901, 1, 0x8055BE00, 0x80301A20, kP227, 1},
        {"BD Hologram", 0x1903, 1, 0x8055BF60, 0x80303CC8, kP228, 2},
        {"BA Switch", 0x1900, 1, 0x8055BE80, 0x803024E4, nullptr, 0},
        {"BA Mine", 0x17D5, 1, 0x8055BD04, 0x80300554, kP230, 4},
        {"SUCTION PILLAR", 0x1902, 1, 0x8055C03C, 0x8030463C, nullptr, 0},
        {"BA GUNSHIP", 0x17D4, 1, 0x8055BB20, 0x802FE7C4, kP232, 9},
        {"BD True", 0x1B58, 1, 0x8055BFC8, 0x803041EC, nullptr, 0},
        {"GadgetStageDataEnd", 0x2583, 1, 0x8052C7BC, 0x00000000, nullptr, 0},
        {"EnemyEntryStart", 0x258E, 2, 0x8053BAB0, 0x00000000, nullptr, 0},
        {"GUN_SOLDIER", 0x0064, 2, 0x80539868, 0x80196E38, kP236, 23},
        {"GUN_BEETLE", 0x0065, 2, 0x80537158, 0x80193DD4, kP237, 18},
        {"GUN_BIGFOOT", 0x0066, 2, 0x8054F964, 0x80287328, kP238, 10},
        {"GUN_ROBOT", 0x0068, 2, 0x805384AC, 0x801952F8, kP239, 27},
        {"BK_GIANT", 0x008C, 2, 0x805508EC, 0x8028892C, kP240, 11},
        {"BK_SOLDIER", 0x008D, 2, 0x80531E70, 0x8018CAD0, kP241, 24},
        {"BK_WINGLARGE", 0x008E, 2, 0x805337C8, 0x8018FFF0, kP242, 15},
        {"BK_WINGSMALL", 0x008F, 2, 0x80534BA0, 0x80191640, kP243, 14},
        {"BK_WORM", 0x0090, 2, 0x80535BEC, 0x801920AC, kP244, 10},
        {"BK_LARVA", 0x0091, 2, 0x80531924, 0x80189864, kP245, 11},
        {"BK_CHAOS", 0x0092, 2, 0x805570B0, 0x802AF70C, kP246, 13},
        {"BK_NINJA", 0x0093, 2, 0x80555C48, 0x802AC298, kP247, 23},
        {"EGG_PAWN", 0x0079, 2, 0x8052D4C4, 0x8017BD90, kP248, 27},
        {"EGG_PIERROT", 0x0078, 2, 0x80551918, 0x80289B84, kP249, 13},
        {"EGG_SHADOWANDROID", 0x007A, 2, 0x80553CB8, 0x8029C600, kP250, 11},
        {"BLACK_BULL_0210", 0x00B4, 2, 0x8054847C, 0x80233030, nullptr, 0},
        {"BLACK_BULL_0412", 0x00B5, 2, 0x8054950C, 0x80243E64, nullptr, 0},
        {"HEAVY_DOG_0410", 0x00B6, 2, 0x8054A26C, 0x8024F058, nullptr, 0},
        {"HEAVY_DOG_0510", 0x00B7, 2, 0x8054AB3C, 0x8025447C, nullptr, 0},
        {"BLACK_DOOM", 0x00B8, 2, 0x8054F400, 0x8028390C, nullptr, 0},
        {"EGG_MECA_0310", 0x00B9, 2, 0x8055AB7C, 0x802EB3A8, nullptr, 0},
        {"EGG_MECA_0411", 0x00BA, 2, 0x8055AA54, 0x802EAD84, nullptr, 0},
        {"EGG_MECA_0511", 0x00BB, 2, 0x8055A914, 0x802EA2DC, nullptr, 0},
        {"", 0x00BC, 2, 0x80559CE8, 0x802D9108, nullptr, 0},
        {"EGG_LASTMECH", 0x00BD, 2, 0x8055B900, 0x802FE428, nullptr, 0},
        {"DEVIL_DOOM", 0x00BE, 2, 0x8055C8AC, 0x8030DBBC, nullptr, 0},
        {"EnemyEntryEnd", 0x258E, 2, 0x8053BAD4, 0x00000000, nullptr, 0},
        {"VehicleDataStart", 0x258C, 1, 0x8053D018, 0x00000000, nullptr, 0},
        {"Noraml Car", 0x0046, 1, 0x8053CA50, 0x00000000, nullptr, 0},
        {"Open Car", 0x0047, 1, 0x8053CA7C, 0x00000000, nullptr, 0},
        {"Armed Car", 0x0048, 1, 0x8053CAA8, 0x00000000, nullptr, 0},
        {"Bike", 0x0049, 1, 0x8053CAD4, 0x00000000, nullptr, 0},
        {"", 0x004A, 4, 0x8053C3E0, 0x00000000, nullptr, 0},
        {"", 0x004B, 4, 0x8053C404, 0x00000000, nullptr, 0},
        {"", 0x004C, 4, 0x8053C5B8, 0x00000000, nullptr, 0},
        {"", 0x004D, 4, 0x8053C74C, 0x00000000, nullptr, 0},
        {"", 0x004E, 4, 0x805590BC, 0x00000000, nullptr, 0},
        {"VehicleDataEnd", 0x258D, 1, 0x8053D03C, 0x00000000, nullptr, 0},
        {"Sonic", 0x0191, 4, 0x8054EA80, 0x00000000, nullptr, 0},
        {"Tails", 0x0192, 4, 0x8054EAA4, 0x00000000, nullptr, 0},
        {"Knuckles", 0x0193, 4, 0x8054EAC8, 0x00000000, nullptr, 0},
        {"Amy", 0x0194, 4, 0x8054EAEC, 0x00000000, nullptr, 0},
        {"Rouge", 0x0195, 4, 0x8054EB10, 0x00000000, nullptr, 0},
        {"Omega", 0x0196, 4, 0x8054EB34, 0x00000000, nullptr, 0},
        {"Vector", 0x0197, 4, 0x8054EB58, 0x00000000, nullptr, 0},
        {"Espio", 0x0198, 4, 0x8054EB7C, 0x00000000, nullptr, 0},
        {"Maria", 0x0199, 4, 0x8054EBA0, 0x00000000, nullptr, 0},
        {"Charmy", 0x019A, 4, 0x8054EBC4, 0x00000000, nullptr, 0},
        {"Eggman", 0x019B, 4, 0x8054EBE8, 0x00000000, nullptr, 0},
        {"DoomsEye", 0x019C, 4, 0x8054EC0C, 0x00000000, nullptr, 0},
    };
    return k;
}

}  // namespace shadow::gameplay
