"""Generate gameplay/src/StageTable.generated.cpp from the DOL stage table.

Stage table: .rodata 0x804C5AE8, 59 records x 0x50 (see MISSION_PARAMETER_MAP.md §2).
Record index == stage index. Per record: id, name, flags, 4 code ptrs, 3 route groups
{next stage index, mission key, id 0x2xx}, hard-mode mission key, 3 unknown words.
"""
import os
from dol import get_dol

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, '..', 'src', 'StageTable.generated.cpp'))
TABLE, COUNT, SIZE = 0x804C5AE8, 59, 0x50


def s32(v):
    return v - (1 << 32) if v & 0x80000000 else v


def main():
    d = get_dol()
    L = ['// GENERATED by tools/gen_stage_table_cpp.py from main.dol 0x804C5AE8 -- do not edit.',
         '#include "shadow/gameplay/Mission.hpp"', '', 'namespace shadow::gameplay {', '',
         'const std::vector<StageTableEntry>& OriginalStageTable() {',
         '    static const std::vector<StageTableEntry> k = {']
    for i in range(COUNT):
        a = TABLE + SIZE * i
        w = [d.u32(a + 4 * k) for k in range(20)]
        name = (d.cstr(w[1]) or b'').decode('latin1')
        routes = ', '.join('{%d, %d, %d}' % (s32(w[7 + 3 * s]), s32(w[8 + 3 * s]), s32(w[9 + 3 * s]))
                           for s in range(3))
        L.append('        {%d, "%s", 0x%X, {%s}, %d},  // [%d] @%08X' % (
            s32(w[0]), name, w[2], routes, s32(w[16]), i, a))
    L += ['    };', '    return k;', '}', '', '}  // namespace shadow::gameplay', '']
    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(L))
    print('wrote', OUT)


if __name__ == '__main__':
    main()
