"""Generate gameplay/src/SetObjCatalog.generated.cpp from data/setobj_catalog.json
(the SET object catalog embedded in main.dol at 0x8052C1A0)."""
import os
import json
from dol import DATA_DIR

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, '..', 'src', 'SetObjCatalog.generated.cpp'))
BS = chr(92)


def s32(h):
    v = int(h, 16)
    return v - (1 << 32) if v & 0x80000000 else v


def flit(x):
    t = '%.9g' % x
    if not any(c in t for c in '.en'):
        t += '.0'
    return t + 'f'


def cstr(s):
    s = (s or '').replace(BS, BS + BS).replace('"', BS + '"')
    return '"' + s + '"'


def main():
    cat = json.load(open(os.path.join(DATA_DIR, 'setobj_catalog.json'), encoding='utf-8'))
    L = ['// GENERATED by tools/gen_catalog_cpp.py from main.dol table 0x8052C1A0 -- do not edit.',
         '#include "shadow/gameplay/SetSystem.hpp"', '', 'namespace shadow::gameplay {', 'namespace {']
    for i, d in enumerate(cat):
        if not d['params']:
            continue
        L.append('const SetParamDesc kP%d[] = {  // %s' % (i, d['name']))
        for p in d['params']:
            r = p['raw']
            fl = p.get('floats') or [0, 0, 0, 0, 0, 0]
            L.append('    {SetParamType(%d), %s, %d, %d, %d, %s, %s, %s},' % (
                p['type'], cstr(p['name']), s32(r[0]), s32(r[1]), s32(r[2]),
                flit(fl[3]), flit(fl[4]), flit(fl[5])))
        L.append('};')
    L += ['}  // namespace', '', 'const std::vector<SetObjDesc>& OriginalSetCatalog() {',
          '    static const std::vector<SetObjDesc> k = {']
    for i, d in enumerate(cat):
        L.append('        {%s, 0x%s, %d, 0x%s, 0x%s, %s, %d},' % (
            cstr(d['name']), d['id'], d['b1A'], d['desc'], d['hook0C'],
            ('kP%d' % i) if d['params'] else 'nullptr', len(d['params'])))
    L += ['    };', '    return k;', '}', '', '}  // namespace shadow::gameplay', '']
    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(L))
    print('wrote', OUT, len(cat), 'descriptors')


if __name__ == '__main__':
    main()
