#include "shadowpc/rhi/VulkanBackend.hpp"
#include <vulkan/vulkan.h>
#include <algorithm>
#include <cstring>
#include <stdexcept>
#include <unordered_map>
#include <vector>
namespace shadowpc::rhi {
namespace {
void vkcheck(VkResult r,const char* msg){if(r!=VK_SUCCESS)throw std::runtime_error(msg);}
VkFormat vkformat(Format f){switch(f){case Format::RGBA8_UNorm:return VK_FORMAT_R8G8B8A8_UNORM;case Format::RGBA8_sRGB:return VK_FORMAT_R8G8B8A8_SRGB;case Format::BC1:return VK_FORMAT_BC1_RGBA_UNORM_BLOCK;case Format::BC3:return VK_FORMAT_BC3_UNORM_BLOCK;case Format::BC4:return VK_FORMAT_BC4_UNORM_BLOCK;case Format::BC5:return VK_FORMAT_BC5_UNORM_BLOCK;case Format::BC7:return VK_FORMAT_BC7_UNORM_BLOCK;case Format::D32_Float:return VK_FORMAT_D32_SFLOAT;default:return VK_FORMAT_UNDEFINED;}}
VkBufferUsageFlags buffer_usage(std::uint32_t u){VkBufferUsageFlags r=VK_BUFFER_USAGE_TRANSFER_DST_BIT;if(u&BufferVertex)r|=VK_BUFFER_USAGE_VERTEX_BUFFER_BIT;if(u&BufferIndex)r|=VK_BUFFER_USAGE_INDEX_BUFFER_BIT;if(u&BufferConstant)r|=VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT;if(u&BufferStorage)r|=VK_BUFFER_USAGE_STORAGE_BUFFER_BIT;return r;}
VkImageUsageFlags texture_usage(std::uint32_t u){VkImageUsageFlags r=VK_IMAGE_USAGE_TRANSFER_DST_BIT;if(u&TextureSampled)r|=VK_IMAGE_USAGE_SAMPLED_BIT;if(u&TextureRenderTarget)r|=VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT;if(u&TextureDepth)r|=VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT;if(u&TextureStorage)r|=VK_IMAGE_USAGE_STORAGE_BIT;return r;}
}
struct VulkanBackend::Impl {
 struct BufferRec{VkBuffer buffer{VK_NULL_HANDLE};VkDeviceMemory memory{VK_NULL_HANDLE};BufferDesc desc;};
 struct TextureRec{VkImage image{VK_NULL_HANDLE};VkDeviceMemory memory{VK_NULL_HANDLE};TextureDesc desc;std::vector<bool> uploaded;};
 struct Pending{VkFence fence{VK_NULL_HANDLE};VkBuffer staging{VK_NULL_HANDLE};VkDeviceMemory staging_memory{VK_NULL_HANDLE};VkCommandPool pool{VK_NULL_HANDLE};};
 VkInstance instance{VK_NULL_HANDLE};VkPhysicalDevice physical{VK_NULL_HANDLE};VkDevice device{VK_NULL_HANDLE};std::uint32_t graphics_family{};VkQueue graphics{VK_NULL_HANDLE};
 std::uint64_t next_handle{1},next_fence{1};std::unordered_map<std::uint64_t,BufferRec> buffers;std::unordered_map<std::uint64_t,TextureRec> textures;mutable std::unordered_map<std::uint64_t,Pending> pending;
 std::uint32_t memory_type(std::uint32_t bits,VkMemoryPropertyFlags wanted)const{VkPhysicalDeviceMemoryProperties mp{};vkGetPhysicalDeviceMemoryProperties(physical,&mp);for(std::uint32_t i=0;i<mp.memoryTypeCount;++i)if((bits&(1u<<i))&&(mp.memoryTypes[i].propertyFlags&wanted)==wanted)return i;throw std::runtime_error("No compatible Vulkan memory type");}
 void create_staging(std::size_t bytes,VkBuffer& b,VkDeviceMemory& m){VkBufferCreateInfo bi{VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO};bi.size=std::max<std::size_t>(1,bytes);bi.usage=VK_BUFFER_USAGE_TRANSFER_SRC_BIT;bi.sharingMode=VK_SHARING_MODE_EXCLUSIVE;vkcheck(vkCreateBuffer(device,&bi,nullptr,&b),"vkCreateBuffer staging failed");VkMemoryRequirements req{};vkGetBufferMemoryRequirements(device,b,&req);VkMemoryAllocateInfo ai{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};ai.allocationSize=req.size;ai.memoryTypeIndex=memory_type(req.memoryTypeBits,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);vkcheck(vkAllocateMemory(device,&ai,nullptr,&m),"vkAllocateMemory staging failed");vkcheck(vkBindBufferMemory(device,b,m,0),"vkBindBufferMemory staging failed");}
 struct Cmd{VkCommandPool pool{};VkCommandBuffer cmd{};};
 Cmd begin_cmd(){VkCommandPoolCreateInfo pi{VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO};pi.flags=VK_COMMAND_POOL_CREATE_TRANSIENT_BIT;pi.queueFamilyIndex=graphics_family;Cmd c{};vkcheck(vkCreateCommandPool(device,&pi,nullptr,&c.pool),"vkCreateCommandPool failed");VkCommandBufferAllocateInfo ai{VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};ai.commandPool=c.pool;ai.level=VK_COMMAND_BUFFER_LEVEL_PRIMARY;ai.commandBufferCount=1;vkcheck(vkAllocateCommandBuffers(device,&ai,&c.cmd),"vkAllocateCommandBuffers failed");VkCommandBufferBeginInfo bi{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};bi.flags=VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;vkcheck(vkBeginCommandBuffer(c.cmd,&bi),"vkBeginCommandBuffer failed");return c;}
 FenceValue submit(Cmd c,VkBuffer staging,VkDeviceMemory staging_mem){vkcheck(vkEndCommandBuffer(c.cmd),"vkEndCommandBuffer failed");VkFenceCreateInfo fi{VK_STRUCTURE_TYPE_FENCE_CREATE_INFO};VkFence f{};vkcheck(vkCreateFence(device,&fi,nullptr,&f),"vkCreateFence failed");VkSubmitInfo si{VK_STRUCTURE_TYPE_SUBMIT_INFO};si.commandBufferCount=1;si.pCommandBuffers=&c.cmd;vkcheck(vkQueueSubmit(graphics,1,&si,f),"vkQueueSubmit failed");auto id=next_fence++;pending.emplace(id,Pending{f,staging,staging_mem,c.pool});return{id};}
 void free_pending(Pending& p)const{if(p.pool)vkDestroyCommandPool(device,p.pool,nullptr);if(p.staging)vkDestroyBuffer(device,p.staging,nullptr);if(p.staging_memory)vkFreeMemory(device,p.staging_memory,nullptr);if(p.fence)vkDestroyFence(device,p.fence,nullptr);p={};}
 void collect(){for(auto it=pending.begin();it!=pending.end();){if(vkGetFenceStatus(device,it->second.fence)==VK_SUCCESS){free_pending(it->second);it=pending.erase(it);}else ++it;}}
};
VulkanBackend::VulkanBackend():impl_(std::make_unique<Impl>()){
 VkApplicationInfo ai{VK_STRUCTURE_TYPE_APPLICATION_INFO};ai.pApplicationName="ShadowPC";ai.applicationVersion=VK_MAKE_API_VERSION(0,1,4,0);ai.pEngineName="ShadowPC";ai.engineVersion=VK_MAKE_API_VERSION(0,1,4,0);ai.apiVersion=VK_API_VERSION_1_3;VkInstanceCreateInfo ci{VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO};ci.pApplicationInfo=&ai;vkcheck(vkCreateInstance(&ci,nullptr,&impl_->instance),"vkCreateInstance failed");
 std::uint32_t n=0;vkcheck(vkEnumeratePhysicalDevices(impl_->instance,&n,nullptr),"vkEnumeratePhysicalDevices failed");if(!n)throw std::runtime_error("No Vulkan GPU");std::vector<VkPhysicalDevice> g(n);vkcheck(vkEnumeratePhysicalDevices(impl_->instance,&n,g.data()),"vkEnumeratePhysicalDevices failed");impl_->physical=g[0];std::uint32_t qn=0;vkGetPhysicalDeviceQueueFamilyProperties(impl_->physical,&qn,nullptr);std::vector<VkQueueFamilyProperties> qp(qn);vkGetPhysicalDeviceQueueFamilyProperties(impl_->physical,&qn,qp.data());bool found=false;for(std::uint32_t i=0;i<qn;++i)if(qp[i].queueFlags&VK_QUEUE_GRAPHICS_BIT){impl_->graphics_family=i;found=true;break;}if(!found)throw std::runtime_error("No Vulkan graphics queue");float prio=1.f;VkDeviceQueueCreateInfo qi{VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO};qi.queueFamilyIndex=impl_->graphics_family;qi.queueCount=1;qi.pQueuePriorities=&prio;VkPhysicalDeviceFeatures features{};features.textureCompressionBC=VK_TRUE;VkDeviceCreateInfo di{VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO};di.queueCreateInfoCount=1;di.pQueueCreateInfos=&qi;di.pEnabledFeatures=&features;vkcheck(vkCreateDevice(impl_->physical,&di,nullptr,&impl_->device),"vkCreateDevice failed");vkGetDeviceQueue(impl_->device,impl_->graphics_family,0,&impl_->graphics);
}
VulkanBackend::~VulkanBackend(){if(!impl_)return;if(impl_->device)vkDeviceWaitIdle(impl_->device);for(auto& [id,p]:impl_->pending){(void)id;impl_->free_pending(p);}for(auto& [id,b]:impl_->buffers){(void)id;if(b.buffer)vkDestroyBuffer(impl_->device,b.buffer,nullptr);if(b.memory)vkFreeMemory(impl_->device,b.memory,nullptr);}for(auto& [id,t]:impl_->textures){(void)id;if(t.image)vkDestroyImage(impl_->device,t.image,nullptr);if(t.memory)vkFreeMemory(impl_->device,t.memory,nullptr);}if(impl_->device)vkDestroyDevice(impl_->device,nullptr);if(impl_->instance)vkDestroyInstance(impl_->instance,nullptr);}
BackendCaps VulkanBackend::caps()const noexcept{return{.async_compute=true,.dedicated_copy_queue=false,.sparse_resources=false,.mesh_shaders=false,.sampler_feedback=false};}
BufferHandle VulkanBackend::create_buffer(const BufferDesc& d){VkBufferCreateInfo bi{VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO};bi.size=std::max<std::uint64_t>(1,d.bytes);bi.usage=buffer_usage(d.usage);if(d.memory==MemoryClass::Upload)bi.usage|=VK_BUFFER_USAGE_TRANSFER_SRC_BIT;bi.sharingMode=VK_SHARING_MODE_EXCLUSIVE;Impl::BufferRec r{};r.desc=d;vkcheck(vkCreateBuffer(impl_->device,&bi,nullptr,&r.buffer),"vkCreateBuffer failed");VkMemoryRequirements req{};vkGetBufferMemoryRequirements(impl_->device,r.buffer,&req);VkMemoryPropertyFlags props=d.memory==MemoryClass::DeviceLocal?VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT:VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT;VkMemoryAllocateInfo ai{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};ai.allocationSize=req.size;ai.memoryTypeIndex=impl_->memory_type(req.memoryTypeBits,props);vkcheck(vkAllocateMemory(impl_->device,&ai,nullptr,&r.memory),"vkAllocateMemory failed");vkcheck(vkBindBufferMemory(impl_->device,r.buffer,r.memory,0),"vkBindBufferMemory failed");auto id=impl_->next_handle++;impl_->buffers.emplace(id,std::move(r));return{id};}
TextureHandle VulkanBackend::create_texture(const TextureDesc& d){Impl::TextureRec r{};r.desc=d;r.uploaded.resize(d.mip_count*d.array_layers,false);VkImageCreateInfo ii{VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO};ii.imageType=d.depth>1?VK_IMAGE_TYPE_3D:VK_IMAGE_TYPE_2D;ii.format=vkformat(d.format);ii.extent={d.width,d.height,d.depth};ii.mipLevels=d.mip_count;ii.arrayLayers=d.depth>1?1:d.array_layers;ii.samples=VK_SAMPLE_COUNT_1_BIT;ii.tiling=VK_IMAGE_TILING_OPTIMAL;ii.usage=texture_usage(d.usage);ii.sharingMode=VK_SHARING_MODE_EXCLUSIVE;ii.initialLayout=VK_IMAGE_LAYOUT_UNDEFINED;vkcheck(vkCreateImage(impl_->device,&ii,nullptr,&r.image),"vkCreateImage failed");VkMemoryRequirements req{};vkGetImageMemoryRequirements(impl_->device,r.image,&req);VkMemoryAllocateInfo ai{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};ai.allocationSize=req.size;ai.memoryTypeIndex=impl_->memory_type(req.memoryTypeBits,VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);vkcheck(vkAllocateMemory(impl_->device,&ai,nullptr,&r.memory),"vkAllocateMemory image failed");vkcheck(vkBindImageMemory(impl_->device,r.image,r.memory,0),"vkBindImageMemory failed");auto id=impl_->next_handle++;impl_->textures.emplace(id,std::move(r));return{id};}
void VulkanBackend::destroy(BufferHandle h){auto it=impl_->buffers.find(h.value);if(it==impl_->buffers.end())return;if(it->second.buffer)vkDestroyBuffer(impl_->device,it->second.buffer,nullptr);if(it->second.memory)vkFreeMemory(impl_->device,it->second.memory,nullptr);impl_->buffers.erase(it);}void VulkanBackend::destroy(TextureHandle h){auto it=impl_->textures.find(h.value);if(it==impl_->textures.end())return;if(it->second.image)vkDestroyImage(impl_->device,it->second.image,nullptr);if(it->second.memory)vkFreeMemory(impl_->device,it->second.memory,nullptr);impl_->textures.erase(it);}
FenceValue VulkanBackend::upload(BufferHandle h,std::uint64_t off,std::span<const std::byte> src){auto it=impl_->buffers.find(h.value);if(it==impl_->buffers.end())throw std::runtime_error("invalid Vulkan buffer handle");auto& dst=it->second;if(off+src.size()>dst.desc.bytes)throw std::runtime_error("Vulkan buffer upload overflow");if(dst.desc.memory!=MemoryClass::DeviceLocal){void* p{};vkcheck(vkMapMemory(impl_->device,dst.memory,off,src.size(),0,&p),"vkMapMemory failed");std::memcpy(p,src.data(),src.size());vkUnmapMemory(impl_->device,dst.memory);return{};}VkBuffer staging{};VkDeviceMemory sm{};impl_->create_staging(src.size(),staging,sm);void* p{};vkcheck(vkMapMemory(impl_->device,sm,0,src.size(),0,&p),"vkMapMemory staging failed");std::memcpy(p,src.data(),src.size());vkUnmapMemory(impl_->device,sm);auto c=impl_->begin_cmd();VkBufferCopy copy{0,off,src.size()};vkCmdCopyBuffer(c.cmd,staging,dst.buffer,1,&copy);return impl_->submit(c,staging,sm);}
FenceValue VulkanBackend::upload(TextureHandle h,std::uint32_t mip,std::span<const std::byte> src){auto it=impl_->textures.find(h.value);if(it==impl_->textures.end())throw std::runtime_error("invalid Vulkan texture handle");auto& dst=it->second;if(mip>=dst.desc.mip_count)throw std::runtime_error("Vulkan mip out of range");VkBuffer staging{};VkDeviceMemory sm{};impl_->create_staging(src.size(),staging,sm);void* p{};vkcheck(vkMapMemory(impl_->device,sm,0,src.size(),0,&p),"vkMapMemory texture staging failed");std::memcpy(p,src.data(),src.size());vkUnmapMemory(impl_->device,sm);auto c=impl_->begin_cmd();const VkImageAspectFlags aspect=dst.desc.format==Format::D32_Float?VK_IMAGE_ASPECT_DEPTH_BIT:VK_IMAGE_ASPECT_COLOR_BIT;VkImageMemoryBarrier b1{VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER};b1.oldLayout=dst.uploaded[mip]?VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL:VK_IMAGE_LAYOUT_UNDEFINED;b1.newLayout=VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;b1.srcQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED;b1.dstQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED;b1.image=dst.image;b1.subresourceRange={aspect,mip,1,0,1};b1.srcAccessMask=dst.uploaded[mip]?VK_ACCESS_SHADER_READ_BIT:0;b1.dstAccessMask=VK_ACCESS_TRANSFER_WRITE_BIT;vkCmdPipelineBarrier(c.cmd,dst.uploaded[mip]?VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT:VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,VK_PIPELINE_STAGE_TRANSFER_BIT,0,0,nullptr,0,nullptr,1,&b1);VkBufferImageCopy region{};region.imageSubresource={aspect,mip,0,1};region.imageExtent={std::max(1u,dst.desc.width>>mip),std::max(1u,dst.desc.height>>mip),1};vkCmdCopyBufferToImage(c.cmd,staging,dst.image,VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,1,&region);VkImageMemoryBarrier b2=b1;b2.oldLayout=VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;b2.newLayout=VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;b2.srcAccessMask=VK_ACCESS_TRANSFER_WRITE_BIT;b2.dstAccessMask=VK_ACCESS_SHADER_READ_BIT;vkCmdPipelineBarrier(c.cmd,VK_PIPELINE_STAGE_TRANSFER_BIT,VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,0,0,nullptr,0,nullptr,1,&b2);dst.uploaded[mip]=true;return impl_->submit(c,staging,sm);}
bool VulkanBackend::completed(FenceValue f)const{if(!f.value)return true;auto it=impl_->pending.find(f.value);if(it==impl_->pending.end())return true;return vkGetFenceStatus(impl_->device,it->second.fence)==VK_SUCCESS;}void VulkanBackend::begin_frame(){impl_->collect();}void VulkanBackend::end_frame(){}
}
